// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAnalyticsTurfSummaries = `-- name: GetAnalyticsTurfSummaries :many
SELECT
    t.id AS turf_id,
    t.name AS turf_name,
    COALESCE(s.total_voters, 0) AS voter_count,
    COALESCE(s.contacted_voters, 0) AS contacted_count
FROM turfs t
LEFT JOIN LATERAL (
    SELECT
        COUNT(DISTINCT v.id) AS total_voters,
        COUNT(DISTINCT cl.voter_id) AS contacted_voters
    FROM voters v
    LEFT JOIN contact_logs cl ON cl.voter_id = v.id AND cl.company_id = $1
    WHERE v.company_id = $1
      AND v.location IS NOT NULL
      AND ST_Contains(t.boundary, v.location)
) s ON true
WHERE t.company_id = $1
  AND t.is_active = true
  AND ($2::uuid[] IS NULL OR t.id = ANY($2))
ORDER BY t.name
`

type GetAnalyticsTurfSummariesParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	TurfIds   []uuid.UUID `json:"turf_ids"`
}

type GetAnalyticsTurfSummariesRow struct {
	TurfID         uuid.UUID `json:"turf_id"`
	TurfName       string    `json:"turf_name"`
	VoterCount     int64     `json:"voter_count"`
	ContactedCount int64     `json:"contacted_count"`
}

// Per-turf voter/contacted counts for dashboard.
func (q *Queries) GetAnalyticsTurfSummaries(ctx context.Context, arg GetAnalyticsTurfSummariesParams) ([]GetAnalyticsTurfSummariesRow, error) {
	rows, err := q.db.Query(ctx, getAnalyticsTurfSummaries, arg.CompanyID, arg.TurfIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAnalyticsTurfSummariesRow{}
	for rows.Next() {
		var i GetAnalyticsTurfSummariesRow
		if err := rows.Scan(
			&i.TurfID,
			&i.TurfName,
			&i.VoterCount,
			&i.ContactedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactStats = `-- name: GetContactStats :one
SELECT
    COUNT(*) FILTER (WHERE contact_type = 'door_knock') AS doors_knocked,
    COUNT(*) FILTER (WHERE contact_type = 'phone') AS calls_made,
    COUNT(*) FILTER (WHERE contact_type = 'text') AS texts_sent,
    COUNT(DISTINCT CASE WHEN outcome NOT IN ('', 'not_home', 'refused') THEN voter_id END) AS successful_contacts,
    COUNT(DISTINCT voter_id) AS unique_voters,
    COUNT(*) FILTER (WHERE sentiment = 1) AS sentiment_1,
    COUNT(*) FILTER (WHERE sentiment = 2) AS sentiment_2,
    COUNT(*) FILTER (WHERE sentiment = 3) AS sentiment_3,
    COUNT(*) FILTER (WHERE sentiment = 4) AS sentiment_4,
    COUNT(*) FILTER (WHERE sentiment = 5) AS sentiment_5
FROM contact_logs
WHERE company_id = $1
  AND created_at >= $2
  AND created_at < $3
  AND ($4::uuid IS NULL OR user_id = $4)
  AND ($5::uuid[] IS NULL OR turf_id = ANY($5))
`

type GetContactStatsParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	Since     time.Time   `json:"since"`
	Until     time.Time   `json:"until"`
	UserID    uuid.UUID   `json:"user_id"`
	TurfIds   []uuid.UUID `json:"turf_ids"`
}

type GetContactStatsRow struct {
	DoorsKnocked       int64 `json:"doors_knocked"`
	CallsMade          int64 `json:"calls_made"`
	TextsSent          int64 `json:"texts_sent"`
	SuccessfulContacts int64 `json:"successful_contacts"`
	UniqueVoters       int64 `json:"unique_voters"`
	Sentiment1         int64 `json:"sentiment_1"`
	Sentiment2         int64 `json:"sentiment_2"`
	Sentiment3         int64 `json:"sentiment_3"`
	Sentiment4         int64 `json:"sentiment_4"`
	Sentiment5         int64 `json:"sentiment_5"`
}

// Scoped contact metrics with date range.
func (q *Queries) GetContactStats(ctx context.Context, arg GetContactStatsParams) (GetContactStatsRow, error) {
	row := q.db.QueryRow(ctx, getContactStats,
		arg.CompanyID,
		arg.Since,
		arg.Until,
		arg.UserID,
		arg.TurfIds,
	)
	var i GetContactStatsRow
	err := row.Scan(
		&i.DoorsKnocked,
		&i.CallsMade,
		&i.TextsSent,
		&i.SuccessfulContacts,
		&i.UniqueVoters,
		&i.Sentiment1,
		&i.Sentiment2,
		&i.Sentiment3,
		&i.Sentiment4,
		&i.Sentiment5,
	)
	return i, err
}

const getContactTrendDay = `-- name: GetContactTrendDay :many
SELECT
    date_trunc('day', created_at AT TIME ZONE 'America/New_York')::date AS day,
    COUNT(*) AS total_contacts,
    COUNT(*) FILTER (WHERE contact_type = 'door_knock') AS door_knocks,
    COUNT(*) FILTER (WHERE contact_type = 'phone') AS calls,
    COUNT(*) FILTER (WHERE contact_type = 'text') AS texts
FROM contact_logs
WHERE company_id = $1
  AND created_at >= $2
  AND created_at < $3
  AND ($4::uuid IS NULL OR user_id = $4)
  AND ($5::uuid[] IS NULL OR turf_id = ANY($5))
GROUP BY day
ORDER BY day
`

type GetContactTrendDayParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	Since     time.Time   `json:"since"`
	Until     time.Time   `json:"until"`
	UserID    uuid.UUID   `json:"user_id"`
	TurfIds   []uuid.UUID `json:"turf_ids"`
}

type GetContactTrendDayRow struct {
	Day           pgtype.Date `json:"day"`
	TotalContacts int64       `json:"total_contacts"`
	DoorKnocks    int64       `json:"door_knocks"`
	Calls         int64       `json:"calls"`
	Texts         int64       `json:"texts"`
}

// Daily contact counts for trend charts.
func (q *Queries) GetContactTrendDay(ctx context.Context, arg GetContactTrendDayParams) ([]GetContactTrendDayRow, error) {
	rows, err := q.db.Query(ctx, getContactTrendDay,
		arg.CompanyID,
		arg.Since,
		arg.Until,
		arg.UserID,
		arg.TurfIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetContactTrendDayRow{}
	for rows.Next() {
		var i GetContactTrendDayRow
		if err := rows.Scan(
			&i.Day,
			&i.TotalContacts,
			&i.DoorKnocks,
			&i.Calls,
			&i.Texts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactTrendWeek = `-- name: GetContactTrendWeek :many
SELECT
    date_trunc('week', created_at AT TIME ZONE 'America/New_York')::date AS day,
    COUNT(*) AS total_contacts,
    COUNT(*) FILTER (WHERE contact_type = 'door_knock') AS door_knocks,
    COUNT(*) FILTER (WHERE contact_type = 'phone') AS calls,
    COUNT(*) FILTER (WHERE contact_type = 'text') AS texts
FROM contact_logs
WHERE company_id = $1
  AND created_at >= $2
  AND created_at < $3
  AND ($4::uuid IS NULL OR user_id = $4)
  AND ($5::uuid[] IS NULL OR turf_id = ANY($5))
GROUP BY day
ORDER BY day
`

type GetContactTrendWeekParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	Since     time.Time   `json:"since"`
	Until     time.Time   `json:"until"`
	UserID    uuid.UUID   `json:"user_id"`
	TurfIds   []uuid.UUID `json:"turf_ids"`
}

type GetContactTrendWeekRow struct {
	Day           pgtype.Date `json:"day"`
	TotalContacts int64       `json:"total_contacts"`
	DoorKnocks    int64       `json:"door_knocks"`
	Calls         int64       `json:"calls"`
	Texts         int64       `json:"texts"`
}

// Weekly contact counts for trend charts.
func (q *Queries) GetContactTrendWeek(ctx context.Context, arg GetContactTrendWeekParams) ([]GetContactTrendWeekRow, error) {
	rows, err := q.db.Query(ctx, getContactTrendWeek,
		arg.CompanyID,
		arg.Since,
		arg.Until,
		arg.UserID,
		arg.TurfIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetContactTrendWeekRow{}
	for rows.Next() {
		var i GetContactTrendWeekRow
		if err := rows.Scan(
			&i.Day,
			&i.TotalContacts,
			&i.DoorKnocks,
			&i.Calls,
			&i.Texts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDisplayNames = `-- name: GetDisplayNames :many
SELECT u.id, u.display_name
FROM users u
JOIN company_memberships cm ON cm.user_id = u.id
WHERE cm.company_id = $1
`

type GetDisplayNamesRow struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
}

// Lookup display names for users in a company.
func (q *Queries) GetDisplayNames(ctx context.Context, companyID uuid.UUID) ([]GetDisplayNamesRow, error) {
	rows, err := q.db.Query(ctx, getDisplayNames, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDisplayNamesRow{}
	for rows.Next() {
		var i GetDisplayNamesRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExportContacts = `-- name: GetExportContacts :many
SELECT
    cl.created_at,
    v.first_name AS voter_first_name,
    v.last_name AS voter_last_name,
    cl.contact_type,
    cl.outcome,
    cl.sentiment,
    u.display_name AS navigator_name,
    t.name AS turf_name
FROM contact_logs cl
LEFT JOIN voters v ON v.id = cl.voter_id
LEFT JOIN users u ON u.id = cl.user_id
LEFT JOIN turfs t ON t.id = cl.turf_id
WHERE cl.company_id = $1
  AND cl.created_at >= $2
  AND cl.created_at < $3
  AND ($4::uuid IS NULL OR cl.user_id = $4)
  AND ($5::uuid[] IS NULL OR cl.turf_id = ANY($5))
ORDER BY cl.created_at DESC
`

type GetExportContactsParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	Since     time.Time   `json:"since"`
	Until     time.Time   `json:"until"`
	UserID    uuid.UUID   `json:"user_id"`
	TurfIds   []uuid.UUID `json:"turf_ids"`
}

type GetExportContactsRow struct {
	CreatedAt      time.Time `json:"created_at"`
	VoterFirstName *string   `json:"voter_first_name"`
	VoterLastName  *string   `json:"voter_last_name"`
	ContactType    string    `json:"contact_type"`
	Outcome        string    `json:"outcome"`
	Sentiment      *int32    `json:"sentiment"`
	NavigatorName  *string   `json:"navigator_name"`
	TurfName       *string   `json:"turf_name"`
}

// Export contact log rows with voter and turf names.
func (q *Queries) GetExportContacts(ctx context.Context, arg GetExportContactsParams) ([]GetExportContactsRow, error) {
	rows, err := q.db.Query(ctx, getExportContacts,
		arg.CompanyID,
		arg.Since,
		arg.Until,
		arg.UserID,
		arg.TurfIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExportContactsRow{}
	for rows.Next() {
		var i GetExportContactsRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.VoterFirstName,
			&i.VoterLastName,
			&i.ContactType,
			&i.Outcome,
			&i.Sentiment,
			&i.NavigatorName,
			&i.TurfName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExportTasks = `-- name: GetExportTasks :many
SELECT
    t.title,
    t.task_type,
    t.status,
    t.priority,
    t.progress_pct,
    t.due_date,
    u.display_name AS created_by_name,
    t.created_at
FROM tasks t
LEFT JOIN users u ON u.id = t.created_by
WHERE t.company_id = $1
  AND ($2::uuid IS NULL OR t.created_by = $2)
ORDER BY t.created_at DESC
`

type GetExportTasksParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type GetExportTasksRow struct {
	Title         string             `json:"title"`
	TaskType      string             `json:"task_type"`
	Status        string             `json:"status"`
	Priority      string             `json:"priority"`
	ProgressPct   int32              `json:"progress_pct"`
	DueDate       pgtype.Timestamptz `json:"due_date"`
	CreatedByName *string            `json:"created_by_name"`
	CreatedAt     time.Time          `json:"created_at"`
}

// Export task data.
func (q *Queries) GetExportTasks(ctx context.Context, arg GetExportTasksParams) ([]GetExportTasksRow, error) {
	rows, err := q.db.Query(ctx, getExportTasks, arg.CompanyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExportTasksRow{}
	for rows.Next() {
		var i GetExportTasksRow
		if err := rows.Scan(
			&i.Title,
			&i.TaskType,
			&i.Status,
			&i.Priority,
			&i.ProgressPct,
			&i.DueDate,
			&i.CreatedByName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExportVoters = `-- name: GetExportVoters :many
SELECT
    v.id,
    v.first_name,
    v.last_name,
    v.res_street_address,
    v.res_city,
    v.res_zip,
    v.party,
    v.status,
    v.registration_date
FROM voters v
WHERE v.company_id = $1
  AND ($2::uuid[] IS NULL OR EXISTS (
    SELECT 1 FROM turfs t
    WHERE t.id = ANY($2)
      AND v.location IS NOT NULL
      AND ST_Contains(t.boundary, v.location)
  ))
ORDER BY v.last_name, v.first_name
`

type GetExportVotersParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	TurfIds   []uuid.UUID `json:"turf_ids"`
}

type GetExportVotersRow struct {
	ID               uuid.UUID `json:"id"`
	FirstName        string    `json:"first_name"`
	LastName         string    `json:"last_name"`
	ResStreetAddress string    `json:"res_street_address"`
	ResCity          string    `json:"res_city"`
	ResZip           string    `json:"res_zip"`
	Party            string    `json:"party"`
	Status           string    `json:"status"`
	RegistrationDate string    `json:"registration_date"`
}

// Export voter data.
func (q *Queries) GetExportVoters(ctx context.Context, arg GetExportVotersParams) ([]GetExportVotersRow, error) {
	rows, err := q.db.Query(ctx, getExportVoters, arg.CompanyID, arg.TurfIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExportVotersRow{}
	for rows.Next() {
		var i GetExportVotersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.ResStreetAddress,
			&i.ResCity,
			&i.ResZip,
			&i.Party,
			&i.Status,
			&i.RegistrationDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNavigatorPerformance = `-- name: GetNavigatorPerformance :many
SELECT
    cl.user_id,
    COUNT(*) FILTER (WHERE cl.contact_type = 'door_knock') AS doors_knocked,
    COUNT(*) FILTER (WHERE cl.contact_type = 'phone') AS calls_made,
    COUNT(*) FILTER (WHERE cl.contact_type = 'text') AS texts_sent,
    COUNT(*) AS total_contacts,
    COUNT(DISTINCT CASE WHEN cl.outcome NOT IN ('', 'not_home', 'refused') THEN cl.voter_id END) AS successful_contacts,
    COUNT(DISTINCT cl.voter_id) AS unique_voters
FROM contact_logs cl
WHERE cl.company_id = $1
  AND cl.created_at >= $2
  AND cl.created_at < $3
  AND ($4::uuid[] IS NULL OR cl.turf_id = ANY($4))
GROUP BY cl.user_id
ORDER BY total_contacts DESC
`

type GetNavigatorPerformanceParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	Since     time.Time   `json:"since"`
	Until     time.Time   `json:"until"`
	TurfIds   []uuid.UUID `json:"turf_ids"`
}

type GetNavigatorPerformanceRow struct {
	UserID             uuid.UUID `json:"user_id"`
	DoorsKnocked       int64     `json:"doors_knocked"`
	CallsMade          int64     `json:"calls_made"`
	TextsSent          int64     `json:"texts_sent"`
	TotalContacts      int64     `json:"total_contacts"`
	SuccessfulContacts int64     `json:"successful_contacts"`
	UniqueVoters       int64     `json:"unique_voters"`
}

// Per-navigator metrics for team/admin performance view.
func (q *Queries) GetNavigatorPerformance(ctx context.Context, arg GetNavigatorPerformanceParams) ([]GetNavigatorPerformanceRow, error) {
	rows, err := q.db.Query(ctx, getNavigatorPerformance,
		arg.CompanyID,
		arg.Since,
		arg.Until,
		arg.TurfIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNavigatorPerformanceRow{}
	for rows.Next() {
		var i GetNavigatorPerformanceRow
		if err := rows.Scan(
			&i.UserID,
			&i.DoorsKnocked,
			&i.CallsMade,
			&i.TextsSent,
			&i.TotalContacts,
			&i.SuccessfulContacts,
			&i.UniqueVoters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskStats = `-- name: GetTaskStats :one
SELECT
    COUNT(*) AS total_tasks,
    COUNT(*) FILTER (WHERE status = 'completed') AS completed_tasks
FROM tasks
WHERE company_id = $1
  AND ($2::uuid IS NULL OR created_by = $2)
`

type GetTaskStatsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type GetTaskStatsRow struct {
	TotalTasks     int64 `json:"total_tasks"`
	CompletedTasks int64 `json:"completed_tasks"`
}

// Task completion summary.
func (q *Queries) GetTaskStats(ctx context.Context, arg GetTaskStatsParams) (GetTaskStatsRow, error) {
	row := q.db.QueryRow(ctx, getTaskStats, arg.CompanyID, arg.UserID)
	var i GetTaskStatsRow
	err := row.Scan(&i.TotalTasks, &i.CompletedTasks)
	return i, err
}
