// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countVoterAccessLogs = `-- name: CountVoterAccessLogs :one
SELECT COUNT(*) FROM voter_access_log WHERE company_id = $1
`

func (q *Queries) CountVoterAccessLogs(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVoterAccessLogs, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listVoterAccessLogs = `-- name: ListVoterAccessLogs :many
SELECT val.id, val.user_id, u.email as user_email, val.voter_id,
       val.access_type, val.turf_id, t.name as turf_name,
       val.details, val.ip_address, val.created_at
FROM voter_access_log val
JOIN users u ON u.id = val.user_id
LEFT JOIN turfs t ON t.id = val.turf_id
WHERE val.company_id = $1
ORDER BY val.created_at DESC
LIMIT $2 OFFSET $3
`

type ListVoterAccessLogsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListVoterAccessLogsRow struct {
	ID         uuid.UUID       `json:"id"`
	UserID     uuid.UUID       `json:"user_id"`
	UserEmail  string          `json:"user_email"`
	VoterID    string          `json:"voter_id"`
	AccessType string          `json:"access_type"`
	TurfID     pgtype.UUID     `json:"turf_id"`
	TurfName   *string         `json:"turf_name"`
	Details    json.RawMessage `json:"details"`
	IpAddress  string          `json:"ip_address"`
	CreatedAt  time.Time       `json:"created_at"`
}

func (q *Queries) ListVoterAccessLogs(ctx context.Context, arg ListVoterAccessLogsParams) ([]ListVoterAccessLogsRow, error) {
	rows, err := q.db.Query(ctx, listVoterAccessLogs, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVoterAccessLogsRow{}
	for rows.Next() {
		var i ListVoterAccessLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.VoterID,
			&i.AccessType,
			&i.TurfID,
			&i.TurfName,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoterAccessLogsByUser = `-- name: ListVoterAccessLogsByUser :many
SELECT val.id, val.voter_id, val.access_type, val.turf_id,
       val.details, val.ip_address, val.created_at
FROM voter_access_log val
WHERE val.company_id = $1 AND val.user_id = $2
ORDER BY val.created_at DESC
LIMIT $3 OFFSET $4
`

type ListVoterAccessLogsByUserParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListVoterAccessLogsByUserRow struct {
	ID         uuid.UUID       `json:"id"`
	VoterID    string          `json:"voter_id"`
	AccessType string          `json:"access_type"`
	TurfID     pgtype.UUID     `json:"turf_id"`
	Details    json.RawMessage `json:"details"`
	IpAddress  string          `json:"ip_address"`
	CreatedAt  time.Time       `json:"created_at"`
}

func (q *Queries) ListVoterAccessLogsByUser(ctx context.Context, arg ListVoterAccessLogsByUserParams) ([]ListVoterAccessLogsByUserRow, error) {
	rows, err := q.db.Query(ctx, listVoterAccessLogsByUser,
		arg.CompanyID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVoterAccessLogsByUserRow{}
	for rows.Next() {
		var i ListVoterAccessLogsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.VoterID,
			&i.AccessType,
			&i.TurfID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logVoterAccess = `-- name: LogVoterAccess :exec
INSERT INTO voter_access_log (company_id, user_id, voter_id, access_type, turf_id, details, ip_address)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type LogVoterAccessParams struct {
	CompanyID  uuid.UUID       `json:"company_id"`
	UserID     uuid.UUID       `json:"user_id"`
	VoterID    string          `json:"voter_id"`
	AccessType string          `json:"access_type"`
	TurfID     pgtype.UUID     `json:"turf_id"`
	Details    json.RawMessage `json:"details"`
	IpAddress  string          `json:"ip_address"`
}

func (q *Queries) LogVoterAccess(ctx context.Context, arg LogVoterAccessParams) error {
	_, err := q.db.Exec(ctx, logVoterAccess,
		arg.CompanyID,
		arg.UserID,
		arg.VoterID,
		arg.AccessType,
		arg.TurfID,
		arg.Details,
		arg.IpAddress,
	)
	return err
}
