// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: call_scripts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCallScript = `-- name: CreateCallScript :one
INSERT INTO call_scripts (company_id, title, content, version, is_active, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, title, content, version, is_active, created_by, created_at, updated_at
`

type CreateCallScriptParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Version   int32     `json:"version"`
	IsActive  bool      `json:"is_active"`
	CreatedBy uuid.UUID `json:"created_by"`
}

// Create a new call script.
func (q *Queries) CreateCallScript(ctx context.Context, arg CreateCallScriptParams) (CallScript, error) {
	row := q.db.QueryRow(ctx, createCallScript,
		arg.CompanyID,
		arg.Title,
		arg.Content,
		arg.Version,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i CallScript
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Content,
		&i.Version,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCallScript = `-- name: GetCallScript :one
SELECT id, company_id, title, content, version, is_active, created_by, created_at, updated_at FROM call_scripts
WHERE id = $1 AND company_id = $2
`

type GetCallScriptParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

// Get a call script by ID and company.
func (q *Queries) GetCallScript(ctx context.Context, arg GetCallScriptParams) (CallScript, error) {
	row := q.db.QueryRow(ctx, getCallScript, arg.ID, arg.CompanyID)
	var i CallScript
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Content,
		&i.Version,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCallScripts = `-- name: ListActiveCallScripts :many
SELECT id, company_id, title, content, version, is_active, created_by, created_at, updated_at FROM call_scripts
WHERE company_id = $1 AND is_active = true
ORDER BY created_at DESC
`

// List active call scripts for a company.
func (q *Queries) ListActiveCallScripts(ctx context.Context, companyID uuid.UUID) ([]CallScript, error) {
	rows, err := q.db.Query(ctx, listActiveCallScripts, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CallScript{}
	for rows.Next() {
		var i CallScript
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Content,
			&i.Version,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pullCallScriptsUpdated = `-- name: PullCallScriptsUpdated :many
SELECT id, company_id, title, content, version, is_active, created_by, created_at, updated_at
FROM call_scripts
WHERE company_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type PullCallScriptsUpdatedParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

// Pull call scripts updated since cursor for sync.
func (q *Queries) PullCallScriptsUpdated(ctx context.Context, arg PullCallScriptsUpdatedParams) ([]CallScript, error) {
	rows, err := q.db.Query(ctx, pullCallScriptsUpdated, arg.CompanyID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CallScript{}
	for rows.Next() {
		var i CallScript
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Content,
			&i.Version,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCallScript = `-- name: UpdateCallScript :exec
UPDATE call_scripts
SET title = $3, content = $4, version = $5, is_active = $6, updated_at = now()
WHERE id = $1 AND company_id = $2
`

type UpdateCallScriptParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Version   int32     `json:"version"`
	IsActive  bool      `json:"is_active"`
}

// Update call script fields.
func (q *Queries) UpdateCallScript(ctx context.Context, arg UpdateCallScriptParams) error {
	_, err := q.db.Exec(ctx, updateCallScript,
		arg.ID,
		arg.CompanyID,
		arg.Title,
		arg.Content,
		arg.Version,
		arg.IsActive,
	)
	return err
}
