// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertTaskVoters implements pgx.CopyFromSource.
type iteratorForInsertTaskVoters struct {
	rows                 []InsertTaskVotersParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertTaskVoters) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertTaskVoters) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TaskID,
		r.rows[0].VoterID,
	}, nil
}

func (r iteratorForInsertTaskVoters) Err() error {
	return nil
}

// Bulk insert task voters for contact_list tasks.
func (q *Queries) InsertTaskVoters(ctx context.Context, arg []InsertTaskVotersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"task_voters"}, []string{"task_id", "voter_id"}, &iteratorForInsertTaskVoters{rows: arg})
}
