// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelEvent = `-- name: CancelEvent :exec
UPDATE events
SET status = 'cancelled', updated_at = now()
WHERE id = $1 AND company_id = $2
`

type CancelEventParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

// Cancel an event.
func (q *Queries) CancelEvent(ctx context.Context, arg CancelEventParams) error {
	_, err := q.db.Exec(ctx, cancelEvent, arg.ID, arg.CompanyID)
	return err
}

const checkInEvent = `-- name: CheckInEvent :one
INSERT INTO event_checkins (event_id, user_id)
VALUES ($1, $2)
ON CONFLICT (event_id, user_id) DO NOTHING
RETURNING id, event_id, user_id, checked_in_at
`

type CheckInEventParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

// Record a check-in at an event.
func (q *Queries) CheckInEvent(ctx context.Context, arg CheckInEventParams) (EventCheckin, error) {
	row := q.db.QueryRow(ctx, checkInEvent, arg.EventID, arg.UserID)
	var i EventCheckin
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.CheckedInAt,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (company_id, title, description, event_type, starts_at, ends_at,
                    location_name, location_lat, location_lng, linked_turf_id, max_attendees, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, company_id, title, description, event_type, status, starts_at, ends_at, location_name, location_lat, location_lng, linked_turf_id, max_attendees, created_by, created_at, updated_at
`

type CreateEventParams struct {
	CompanyID    uuid.UUID   `json:"company_id"`
	Title        string      `json:"title"`
	Description  string      `json:"description"`
	EventType    string      `json:"event_type"`
	StartsAt     time.Time   `json:"starts_at"`
	EndsAt       time.Time   `json:"ends_at"`
	LocationName *string     `json:"location_name"`
	LocationLat  *float64    `json:"location_lat"`
	LocationLng  *float64    `json:"location_lng"`
	LinkedTurfID pgtype.UUID `json:"linked_turf_id"`
	MaxAttendees *int32      `json:"max_attendees"`
	CreatedBy    uuid.UUID   `json:"created_by"`
}

// Create a new event.
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.CompanyID,
		arg.Title,
		arg.Description,
		arg.EventType,
		arg.StartsAt,
		arg.EndsAt,
		arg.LocationName,
		arg.LocationLat,
		arg.LocationLng,
		arg.LinkedTurfID,
		arg.MaxAttendees,
		arg.CreatedBy,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.EventType,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.LocationName,
		&i.LocationLat,
		&i.LocationLng,
		&i.LinkedTurfID,
		&i.MaxAttendees,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRSVP = `-- name: DeleteRSVP :exec
DELETE FROM event_rsvps
WHERE event_id = $1 AND user_id = $2
`

type DeleteRSVPParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

// Delete an RSVP.
func (q *Queries) DeleteRSVP(ctx context.Context, arg DeleteRSVPParams) error {
	_, err := q.db.Exec(ctx, deleteRSVP, arg.EventID, arg.UserID)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, company_id, title, description, event_type, status, starts_at, ends_at, location_name, location_lat, location_lng, linked_turf_id, max_attendees, created_by, created_at, updated_at FROM events
WHERE id = $1 AND company_id = $2
`

type GetEventParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

// Get an event by ID and company.
func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, arg.ID, arg.CompanyID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.EventType,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.LocationName,
		&i.LocationLat,
		&i.LocationLng,
		&i.LinkedTurfID,
		&i.MaxAttendees,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventCheckins = `-- name: GetEventCheckins :many
SELECT ec.id, ec.event_id, ec.user_id, ec.checked_in_at,
       u.display_name
FROM event_checkins ec
JOIN users u ON u.id = ec.user_id
WHERE ec.event_id = $1
`

type GetEventCheckinsRow struct {
	ID          uuid.UUID `json:"id"`
	EventID     uuid.UUID `json:"event_id"`
	UserID      uuid.UUID `json:"user_id"`
	CheckedInAt time.Time `json:"checked_in_at"`
	DisplayName string    `json:"display_name"`
}

// Get check-ins for an event with user display names.
func (q *Queries) GetEventCheckins(ctx context.Context, eventID uuid.UUID) ([]GetEventCheckinsRow, error) {
	rows, err := q.db.Query(ctx, getEventCheckins, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventCheckinsRow{}
	for rows.Next() {
		var i GetEventCheckinsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.CheckedInAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventRSVPCount = `-- name: GetEventRSVPCount :one
SELECT COUNT(*)::int AS count FROM event_rsvps
WHERE event_id = $1 AND status = 'going'
`

// Count RSVPs with status 'going' for an event.
func (q *Queries) GetEventRSVPCount(ctx context.Context, eventID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getEventRSVPCount, eventID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getEventRSVPs = `-- name: GetEventRSVPs :many
SELECT er.id, er.event_id, er.user_id, er.status, er.created_at,
       u.display_name
FROM event_rsvps er
JOIN users u ON u.id = er.user_id
WHERE er.event_id = $1
`

type GetEventRSVPsRow struct {
	ID          uuid.UUID `json:"id"`
	EventID     uuid.UUID `json:"event_id"`
	UserID      uuid.UUID `json:"user_id"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	DisplayName string    `json:"display_name"`
}

// Get RSVPs for an event with user display names.
func (q *Queries) GetEventRSVPs(ctx context.Context, eventID uuid.UUID) ([]GetEventRSVPsRow, error) {
	rows, err := q.db.Query(ctx, getEventRSVPs, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventRSVPsRow{}
	for rows.Next() {
		var i GetEventRSVPsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsStartingSoon = `-- name: GetEventsStartingSoon :many
SELECT id, company_id, title, description, event_type, status, starts_at, ends_at, location_name, location_lat, location_lng, linked_turf_id, max_attendees, created_by, created_at, updated_at FROM events
WHERE starts_at BETWEEN now() AND now() + interval '24 hours'
  AND status = 'scheduled'
`

// Get events starting within the next 24 hours that are still scheduled.
func (q *Queries) GetEventsStartingSoon(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsStartingSoon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.EventType,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.LocationName,
			&i.LocationLat,
			&i.LocationLng,
			&i.LinkedTurfID,
			&i.MaxAttendees,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRSVPsNeedingReminder = `-- name: GetRSVPsNeedingReminder :many
SELECT id, event_id, user_id, status, last_reminder_sent_at, created_at FROM event_rsvps
WHERE event_id = $1
  AND status = 'going'
  AND (last_reminder_sent_at IS NULL OR last_reminder_sent_at < $2)
`

type GetRSVPsNeedingReminderParams struct {
	EventID            uuid.UUID          `json:"event_id"`
	LastReminderSentAt pgtype.Timestamptz `json:"last_reminder_sent_at"`
}

// Get RSVPs that need a reminder (going, not reminded within threshold).
func (q *Queries) GetRSVPsNeedingReminder(ctx context.Context, arg GetRSVPsNeedingReminderParams) ([]EventRsvp, error) {
	rows, err := q.db.Query(ctx, getRSVPsNeedingReminder, arg.EventID, arg.LastReminderSentAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventRsvp{}
	for rows.Next() {
		var i EventRsvp
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.Status,
			&i.LastReminderSentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByCompany = `-- name: ListEventsByCompany :many
SELECT id, company_id, title, description, event_type, status, starts_at, ends_at, location_name, location_lat, location_lng, linked_turf_id, max_attendees, created_by, created_at, updated_at FROM events
WHERE company_id = $1
ORDER BY starts_at DESC
`

// List events for a company, ordered by starts_at DESC.
func (q *Queries) ListEventsByCompany(ctx context.Context, companyID uuid.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.EventType,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.LocationName,
			&i.LocationLat,
			&i.LocationLng,
			&i.LinkedTurfID,
			&i.MaxAttendees,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pullEventRSVPsForEvents = `-- name: PullEventRSVPsForEvents :many
SELECT er.id, er.event_id, er.user_id, er.status, er.last_reminder_sent_at, er.created_at FROM event_rsvps er
JOIN events e ON e.id = er.event_id
WHERE e.company_id = $1 AND er.created_at > $2
ORDER BY er.created_at ASC
LIMIT $3
`

type PullEventRSVPsForEventsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	CreatedAt time.Time `json:"created_at"`
	Limit     int32     `json:"limit"`
}

// Pull RSVPs for a set of events (used after PullEventsUpdated).
func (q *Queries) PullEventRSVPsForEvents(ctx context.Context, arg PullEventRSVPsForEventsParams) ([]EventRsvp, error) {
	rows, err := q.db.Query(ctx, pullEventRSVPsForEvents, arg.CompanyID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventRsvp{}
	for rows.Next() {
		var i EventRsvp
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.Status,
			&i.LastReminderSentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pullEventsUpdated = `-- name: PullEventsUpdated :many
SELECT id, company_id, title, description, event_type, status, starts_at, ends_at, location_name, location_lat, location_lng, linked_turf_id, max_attendees, created_by, created_at, updated_at FROM events
WHERE company_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type PullEventsUpdatedParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

// Pull events updated since cursor for sync.
func (q *Queries) PullEventsUpdated(ctx context.Context, arg PullEventsUpdatedParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, pullEventsUpdated, arg.CompanyID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.EventType,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.LocationName,
			&i.LocationLat,
			&i.LocationLng,
			&i.LinkedTurfID,
			&i.MaxAttendees,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pullTrainingMaterialsUpdated = `-- name: PullTrainingMaterialsUpdated :many
SELECT id, company_id, title, description, content_url, sort_order, is_published, created_by, created_at, updated_at FROM training_materials
WHERE company_id = $1 AND updated_at > $2 AND is_published = true
ORDER BY updated_at ASC
LIMIT $3
`

type PullTrainingMaterialsUpdatedParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

// Pull published training materials updated since cursor for sync.
func (q *Queries) PullTrainingMaterialsUpdated(ctx context.Context, arg PullTrainingMaterialsUpdatedParams) ([]TrainingMaterial, error) {
	rows, err := q.db.Query(ctx, pullTrainingMaterialsUpdated, arg.CompanyID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainingMaterial{}
	for rows.Next() {
		var i TrainingMaterial
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.ContentUrl,
			&i.SortOrder,
			&i.IsPublished,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rSVPEvent = `-- name: RSVPEvent :one
INSERT INTO event_rsvps (event_id, user_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (event_id, user_id) DO UPDATE
SET status = EXCLUDED.status
RETURNING id, event_id, user_id, status, last_reminder_sent_at, created_at
`

type RSVPEventParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
	Status  string    `json:"status"`
}

// Create or update an RSVP for an event.
func (q *Queries) RSVPEvent(ctx context.Context, arg RSVPEventParams) (EventRsvp, error) {
	row := q.db.QueryRow(ctx, rSVPEvent, arg.EventID, arg.UserID, arg.Status)
	var i EventRsvp
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.LastReminderSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = $3, description = $4, event_type = $5,
    starts_at = $6, ends_at = $7,
    location_name = $8, location_lat = $9, location_lng = $10,
    linked_turf_id = $11, max_attendees = $12,
    updated_at = now()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, title, description, event_type, status, starts_at, ends_at, location_name, location_lat, location_lng, linked_turf_id, max_attendees, created_by, created_at, updated_at
`

type UpdateEventParams struct {
	ID           uuid.UUID   `json:"id"`
	CompanyID    uuid.UUID   `json:"company_id"`
	Title        string      `json:"title"`
	Description  string      `json:"description"`
	EventType    string      `json:"event_type"`
	StartsAt     time.Time   `json:"starts_at"`
	EndsAt       time.Time   `json:"ends_at"`
	LocationName *string     `json:"location_name"`
	LocationLat  *float64    `json:"location_lat"`
	LocationLng  *float64    `json:"location_lng"`
	LinkedTurfID pgtype.UUID `json:"linked_turf_id"`
	MaxAttendees *int32      `json:"max_attendees"`
}

// Update an existing event.
func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.CompanyID,
		arg.Title,
		arg.Description,
		arg.EventType,
		arg.StartsAt,
		arg.EndsAt,
		arg.LocationName,
		arg.LocationLat,
		arg.LocationLng,
		arg.LinkedTurfID,
		arg.MaxAttendees,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.EventType,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.LocationName,
		&i.LocationLat,
		&i.LocationLng,
		&i.LinkedTurfID,
		&i.MaxAttendees,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRSVPReminderSent = `-- name: UpdateRSVPReminderSent :exec
UPDATE event_rsvps
SET last_reminder_sent_at = now()
WHERE id = $1
`

// Mark an RSVP as having been sent a reminder.
func (q *Queries) UpdateRSVPReminderSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateRSVPReminderSent, id)
	return err
}
