// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: imports.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const cleanupStaging = `-- name: CleanupStaging :exec
DELETE FROM import_staging WHERE import_job_id = $1
`

func (q *Queries) CleanupStaging(ctx context.Context, importJobID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cleanupStaging, importJobID)
	return err
}

const countImportJobs = `-- name: CountImportJobs :one
SELECT COUNT(*) FROM import_jobs WHERE company_id = $1
`

func (q *Queries) CountImportJobs(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countImportJobs, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStagingRows = `-- name: CountStagingRows :one
SELECT
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE is_valid = true) AS valid,
    COUNT(*) FILTER (WHERE is_valid = false) AS invalid
FROM import_staging
WHERE import_job_id = $1
`

type CountStagingRowsRow struct {
	Total   int64 `json:"total"`
	Valid   int64 `json:"valid"`
	Invalid int64 `json:"invalid"`
}

func (q *Queries) CountStagingRows(ctx context.Context, importJobID uuid.UUID) (CountStagingRowsRow, error) {
	row := q.db.QueryRow(ctx, countStagingRows, importJobID)
	var i CountStagingRowsRow
	err := row.Scan(&i.Total, &i.Valid, &i.Invalid)
	return i, err
}

const createImportJob = `-- name: CreateImportJob :one
INSERT INTO import_jobs (company_id, uploaded_by, file_name, file_storage_key, source_type, field_mapping)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, uploaded_by, file_name, file_storage_key, source_type, status, total_rows, parsed_rows, merged_rows, skipped_rows, error_rows, geocoded_rows, errors, field_mapping, created_at, updated_at
`

type CreateImportJobParams struct {
	CompanyID      uuid.UUID       `json:"company_id"`
	UploadedBy     uuid.UUID       `json:"uploaded_by"`
	FileName       string          `json:"file_name"`
	FileStorageKey string          `json:"file_storage_key"`
	SourceType     string          `json:"source_type"`
	FieldMapping   json.RawMessage `json:"field_mapping"`
}

func (q *Queries) CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, createImportJob,
		arg.CompanyID,
		arg.UploadedBy,
		arg.FileName,
		arg.FileStorageKey,
		arg.SourceType,
		arg.FieldMapping,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UploadedBy,
		&i.FileName,
		&i.FileStorageKey,
		&i.SourceType,
		&i.Status,
		&i.TotalRows,
		&i.ParsedRows,
		&i.MergedRows,
		&i.SkippedRows,
		&i.ErrorRows,
		&i.GeocodedRows,
		&i.Errors,
		&i.FieldMapping,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportJob = `-- name: GetImportJob :one
SELECT id, company_id, uploaded_by, file_name, file_storage_key, source_type, status, total_rows, parsed_rows, merged_rows, skipped_rows, error_rows, geocoded_rows, errors, field_mapping, created_at, updated_at FROM import_jobs WHERE id = $1
`

func (q *Queries) GetImportJob(ctx context.Context, id uuid.UUID) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJob, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UploadedBy,
		&i.FileName,
		&i.FileStorageKey,
		&i.SourceType,
		&i.Status,
		&i.TotalRows,
		&i.ParsedRows,
		&i.MergedRows,
		&i.SkippedRows,
		&i.ErrorRows,
		&i.GeocodedRows,
		&i.Errors,
		&i.FieldMapping,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listImportJobs = `-- name: ListImportJobs :many
SELECT id, company_id, uploaded_by, file_name, file_storage_key, source_type, status, total_rows, parsed_rows, merged_rows, skipped_rows, error_rows, geocoded_rows, errors, field_mapping, created_at, updated_at FROM import_jobs
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListImportJobsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListImportJobs(ctx context.Context, arg ListImportJobsParams) ([]ImportJob, error) {
	rows, err := q.db.Query(ctx, listImportJobs, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportJob{}
	for rows.Next() {
		var i ImportJob
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UploadedBy,
			&i.FileName,
			&i.FileStorageKey,
			&i.SourceType,
			&i.Status,
			&i.TotalRows,
			&i.ParsedRows,
			&i.MergedRows,
			&i.SkippedRows,
			&i.ErrorRows,
			&i.GeocodedRows,
			&i.Errors,
			&i.FieldMapping,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeStagingToVoters = `-- name: MergeStagingToVoters :exec
INSERT INTO voters (
    company_id, first_name, middle_name, last_name, suffix, year_of_birth,
    res_street_address, res_street_number, res_street_name, res_unit,
    res_city, res_state, res_zip,
    mail_street_address, mail_city, mail_state, mail_zip,
    party, status, registration_date,
    county, municipality, ward, precinct,
    congressional_district, state_senate_district, state_house_district,
    source_voter_id, source, dedup_key, voting_history,
    phone, email
)
SELECT
    $2, s.first_name, s.middle_name, s.last_name, s.suffix, s.year_of_birth,
    s.res_street_address, s.res_street_number, s.res_street_name, s.res_unit,
    s.res_city, s.res_state, s.res_zip,
    s.mail_street_address, s.mail_city, s.mail_state, s.mail_zip,
    s.party, s.status, s.registration_date,
    s.county, s.municipality, s.ward, s.precinct,
    s.congressional_district, s.state_senate_district, s.state_house_district,
    s.source_voter_id, $3, s.dedup_key, s.voting_history,
    s.phone, s.email
FROM import_staging s
WHERE s.import_job_id = $1 AND s.is_valid = true
ON CONFLICT (company_id, dedup_key) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    middle_name = EXCLUDED.middle_name,
    suffix = EXCLUDED.suffix,
    res_street_address = EXCLUDED.res_street_address,
    res_unit = EXCLUDED.res_unit,
    res_city = EXCLUDED.res_city,
    res_state = EXCLUDED.res_state,
    res_zip = EXCLUDED.res_zip,
    mail_street_address = EXCLUDED.mail_street_address,
    mail_city = EXCLUDED.mail_city,
    mail_state = EXCLUDED.mail_state,
    mail_zip = EXCLUDED.mail_zip,
    party = EXCLUDED.party,
    status = EXCLUDED.status,
    registration_date = EXCLUDED.registration_date,
    county = EXCLUDED.county,
    municipality = EXCLUDED.municipality,
    ward = EXCLUDED.ward,
    precinct = EXCLUDED.precinct,
    congressional_district = EXCLUDED.congressional_district,
    state_senate_district = EXCLUDED.state_senate_district,
    state_house_district = EXCLUDED.state_house_district,
    source_voter_id = EXCLUDED.source_voter_id,
    source = EXCLUDED.source,
    voting_history = EXCLUDED.voting_history,
    phone = EXCLUDED.phone,
    email = EXCLUDED.email,
    updated_at = now()
`

type MergeStagingToVotersParams struct {
	ImportJobID uuid.UUID `json:"import_job_id"`
	CompanyID   uuid.UUID `json:"company_id"`
	Source      string    `json:"source"`
}

func (q *Queries) MergeStagingToVoters(ctx context.Context, arg MergeStagingToVotersParams) error {
	_, err := q.db.Exec(ctx, mergeStagingToVoters, arg.ImportJobID, arg.CompanyID, arg.Source)
	return err
}

const updateImportJobStatus = `-- name: UpdateImportJobStatus :exec
UPDATE import_jobs SET
    status = $2,
    total_rows = $3,
    parsed_rows = $4,
    merged_rows = $5,
    skipped_rows = $6,
    error_rows = $7,
    errors = $8,
    updated_at = now()
WHERE id = $1
`

type UpdateImportJobStatusParams struct {
	ID          uuid.UUID       `json:"id"`
	Status      string          `json:"status"`
	TotalRows   int32           `json:"total_rows"`
	ParsedRows  int32           `json:"parsed_rows"`
	MergedRows  int32           `json:"merged_rows"`
	SkippedRows int32           `json:"skipped_rows"`
	ErrorRows   int32           `json:"error_rows"`
	Errors      json.RawMessage `json:"errors"`
}

func (q *Queries) UpdateImportJobStatus(ctx context.Context, arg UpdateImportJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateImportJobStatus,
		arg.ID,
		arg.Status,
		arg.TotalRows,
		arg.ParsedRows,
		arg.MergedRows,
		arg.SkippedRows,
		arg.ErrorRows,
		arg.Errors,
	)
	return err
}
