// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         uuid.UUID       `json:"id"`
	CompanyID  uuid.UUID       `json:"company_id"`
	ActorID    uuid.UUID       `json:"actor_id"`
	Action     string          `json:"action"`
	Resource   string          `json:"resource"`
	ResourceID string          `json:"resource_id"`
	Details    json.RawMessage `json:"details"`
	IpAddress  string          `json:"ip_address"`
	CreatedAt  time.Time       `json:"created_at"`
}

type Company struct {
	ID                   uuid.UUID       `json:"id"`
	Name                 string          `json:"name"`
	Slug                 string          `json:"slug"`
	ParentCompanyID      pgtype.UUID     `json:"parent_company_id"`
	CompanyType          string          `json:"company_type"`
	InheritedRoleCap     *int32          `json:"inherited_role_cap"`
	InheritedAccessLevel *string         `json:"inherited_access_level"`
	Settings             json.RawMessage `json:"settings"`
	IsActive             bool            `json:"is_active"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
}

type CompanyHierarchy struct {
	AncestorID   uuid.UUID `json:"ancestor_id"`
	DescendantID uuid.UUID `json:"descendant_id"`
	Generations  int32     `json:"generations"`
}

type CompanyMembership struct {
	ID                  uuid.UUID `json:"id"`
	CompanyID           uuid.UUID `json:"company_id"`
	UserID              uuid.UUID `json:"user_id"`
	RoleID              uuid.UUID `json:"role_id"`
	PermissionOverrides []byte    `json:"permission_overrides"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type DeviceToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	Platform  string    `json:"platform"`
	CreatedAt time.Time `json:"created_at"`
}

type EncryptedCredential struct {
	ID             uuid.UUID `json:"id"`
	CompanyID      uuid.UUID `json:"company_id"`
	CredentialType string    `json:"credential_type"`
	EncryptedValue []byte    `json:"encrypted_value"`
	BlindIndex     string    `json:"blind_index"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type OauthCredential struct {
	ID           uuid.UUID          `json:"id"`
	CompanyID    uuid.UUID          `json:"company_id"`
	UserID       uuid.UUID          `json:"user_id"`
	Provider     string             `json:"provider"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	TokenExpiry  pgtype.Timestamptz `json:"token_expiry"`
	Scopes       []string           `json:"scopes"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type Permission struct {
	ID          uuid.UUID `json:"id"`
	Feature     string    `json:"feature"`
	Action      string    `json:"action"`
	Resource    string    `json:"resource"`
	Description string    `json:"description"`
}

type RefreshToken struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	TokenHash    string             `json:"token_hash"`
	Revoked      bool               `json:"revoked"`
	ExpiresAt    time.Time          `json:"expires_at"`
	CreatedAt    time.Time          `json:"created_at"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
}

type Role struct {
	ID          uuid.UUID   `json:"id"`
	CompanyID   pgtype.UUID `json:"company_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Level       int32       `json:"level"`
	IsSystem    bool        `json:"is_system"`
	CreatedAt   time.Time   `json:"created_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type SsoConfig struct {
	ID           uuid.UUID `json:"id"`
	CompanyID    uuid.UUID `json:"company_id"`
	Provider     string    `json:"provider"`
	IssuerUrl    string    `json:"issuer_url"`
	ClientID     string    `json:"client_id"`
	ClientSecret string    `json:"client_secret"`
	MetadataUrl  string    `json:"metadata_url"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	DisplayName  string    `json:"display_name"`
	ExtraScopes  []string  `json:"extra_scopes"`
	EnforceSso   bool      `json:"enforce_sso"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type TeamAssignment struct {
	ID               uuid.UUID `json:"id"`
	SuperNavigatorID uuid.UUID `json:"super_navigator_id"`
	NavigatorID      uuid.UUID `json:"navigator_id"`
	CompanyID        uuid.UUID `json:"company_id"`
	AssignedBy       uuid.UUID `json:"assigned_by"`
	AssignedAt       time.Time `json:"assigned_at"`
}

type Turf struct {
	ID          uuid.UUID   `json:"id"`
	CompanyID   uuid.UUID   `json:"company_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Boundary    interface{} `json:"boundary"`
	IsActive    bool        `json:"is_active"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type TurfAssignment struct {
	ID         uuid.UUID `json:"id"`
	TurfID     uuid.UUID `json:"turf_id"`
	UserID     uuid.UUID `json:"user_id"`
	AssignedBy uuid.UUID `json:"assigned_by"`
	AssignedAt time.Time `json:"assigned_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	DisplayName  string    `json:"display_name"`
	AvatarUrl    string    `json:"avatar_url"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type VoterAccessLog struct {
	ID         uuid.UUID       `json:"id"`
	CompanyID  uuid.UUID       `json:"company_id"`
	UserID     uuid.UUID       `json:"user_id"`
	VoterID    string          `json:"voter_id"`
	AccessType string          `json:"access_type"`
	TurfID     pgtype.UUID     `json:"turf_id"`
	Details    json.RawMessage `json:"details"`
	IpAddress  string          `json:"ip_address"`
	CreatedAt  time.Time       `json:"created_at"`
}

type Webhook struct {
	ID               uuid.UUID `json:"id"`
	CompanyID        uuid.UUID `json:"company_id"`
	Url              string    `json:"url"`
	Secret           string    `json:"secret"`
	Events           []string  `json:"events"`
	Active           bool      `json:"active"`
	ConsecutiveFails int32     `json:"consecutive_fails"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type WebhookDelivery struct {
	ID           uuid.UUID          `json:"id"`
	WebhookID    uuid.UUID          `json:"webhook_id"`
	EventType    string             `json:"event_type"`
	Payload      string             `json:"payload"`
	Status       string             `json:"status"`
	StatusCode   int32              `json:"status_code"`
	ResponseBody string             `json:"response_body"`
	Attempts     int32              `json:"attempts"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt    time.Time          `json:"created_at"`
}
