// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sms.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countConversationMessages = `-- name: CountConversationMessages :one
SELECT COUNT(*) FROM sms_messages
WHERE company_id = $1 AND voter_id = $2
`

type CountConversationMessagesParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	VoterID   uuid.UUID `json:"voter_id"`
}

func (q *Queries) CountConversationMessages(ctx context.Context, arg CountConversationMessagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConversationMessages, arg.CompanyID, arg.VoterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSMSCampaign = `-- name: CreateSMSCampaign :one
INSERT INTO sms_campaigns (company_id, name, template_id, segment_filters, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type CreateSMSCampaignParams struct {
	CompanyID      uuid.UUID       `json:"company_id"`
	Name           string          `json:"name"`
	TemplateID     pgtype.UUID     `json:"template_id"`
	SegmentFilters json.RawMessage `json:"segment_filters"`
	CreatedBy      uuid.UUID       `json:"created_by"`
}

type CreateSMSCampaignRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateSMSCampaign(ctx context.Context, arg CreateSMSCampaignParams) (CreateSMSCampaignRow, error) {
	row := q.db.QueryRow(ctx, createSMSCampaign,
		arg.CompanyID,
		arg.Name,
		arg.TemplateID,
		arg.SegmentFilters,
		arg.CreatedBy,
	)
	var i CreateSMSCampaignRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createSMSTemplate = `-- name: CreateSMSTemplate :one
INSERT INTO sms_templates (company_id, name, body, merge_fields, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type CreateSMSTemplateParams struct {
	CompanyID   uuid.UUID `json:"company_id"`
	Name        string    `json:"name"`
	Body        string    `json:"body"`
	MergeFields []string  `json:"merge_fields"`
	CreatedBy   uuid.UUID `json:"created_by"`
}

type CreateSMSTemplateRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateSMSTemplate(ctx context.Context, arg CreateSMSTemplateParams) (CreateSMSTemplateRow, error) {
	row := q.db.QueryRow(ctx, createSMSTemplate,
		arg.CompanyID,
		arg.Name,
		arg.Body,
		arg.MergeFields,
		arg.CreatedBy,
	)
	var i CreateSMSTemplateRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteSMSTemplate = `-- name: DeleteSMSTemplate :exec
UPDATE sms_templates SET is_active = false, updated_at = now()
WHERE id = $1 AND company_id = $2
`

type DeleteSMSTemplateParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) DeleteSMSTemplate(ctx context.Context, arg DeleteSMSTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteSMSTemplate, arg.ID, arg.CompanyID)
	return err
}

const getSMSCampaign = `-- name: GetSMSCampaign :one
SELECT id, company_id, name, template_id, segment_filters, status, total_recipients, sent_count, delivered_count, failed_count, created_by, launched_at, completed_at, created_at, updated_at FROM sms_campaigns
WHERE id = $1 AND company_id = $2
`

type GetSMSCampaignParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetSMSCampaign(ctx context.Context, arg GetSMSCampaignParams) (SmsCampaign, error) {
	row := q.db.QueryRow(ctx, getSMSCampaign, arg.ID, arg.CompanyID)
	var i SmsCampaign
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.TemplateID,
		&i.SegmentFilters,
		&i.Status,
		&i.TotalRecipients,
		&i.SentCount,
		&i.DeliveredCount,
		&i.FailedCount,
		&i.CreatedBy,
		&i.LaunchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSMSConfig = `-- name: GetSMSConfig :one
SELECT company_id, twilio_account_sid, twilio_auth_token_encrypted, p2p_messaging_service_sid, a2p_messaging_service_sid, inbound_webhook_url, status_webhook_url, quiet_hours_start, quiet_hours_end, ten_dlc_brand_sid, ten_dlc_campaign_sid, ten_dlc_status, created_at, updated_at FROM sms_config WHERE company_id = $1
`

func (q *Queries) GetSMSConfig(ctx context.Context, companyID uuid.UUID) (SmsConfig, error) {
	row := q.db.QueryRow(ctx, getSMSConfig, companyID)
	var i SmsConfig
	err := row.Scan(
		&i.CompanyID,
		&i.TwilioAccountSid,
		&i.TwilioAuthTokenEncrypted,
		&i.P2pMessagingServiceSid,
		&i.A2pMessagingServiceSid,
		&i.InboundWebhookUrl,
		&i.StatusWebhookUrl,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.TenDlcBrandSid,
		&i.TenDlcCampaignSid,
		&i.TenDlcStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSMSMessageByTwilioSid = `-- name: GetSMSMessageByTwilioSid :one
SELECT id, company_id, voter_id, user_id, campaign_id, direction, message_type, from_number, to_number, body, twilio_message_sid, status, error_code, segments, created_at, updated_at FROM sms_messages WHERE twilio_message_sid = $1
`

func (q *Queries) GetSMSMessageByTwilioSid(ctx context.Context, twilioMessageSid *string) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, getSMSMessageByTwilioSid, twilioMessageSid)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.VoterID,
		&i.UserID,
		&i.CampaignID,
		&i.Direction,
		&i.MessageType,
		&i.FromNumber,
		&i.ToNumber,
		&i.Body,
		&i.TwilioMessageSid,
		&i.Status,
		&i.ErrorCode,
		&i.Segments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSMSMessageCampaignID = `-- name: GetSMSMessageCampaignID :one
SELECT campaign_id FROM sms_messages WHERE twilio_message_sid = $1
`

func (q *Queries) GetSMSMessageCampaignID(ctx context.Context, twilioMessageSid *string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSMSMessageCampaignID, twilioMessageSid)
	var campaign_id pgtype.UUID
	err := row.Scan(&campaign_id)
	return campaign_id, err
}

const getSMSTemplate = `-- name: GetSMSTemplate :one
SELECT id, company_id, name, body, merge_fields, created_by, is_active, created_at, updated_at FROM sms_templates
WHERE id = $1 AND company_id = $2
`

type GetSMSTemplateParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetSMSTemplate(ctx context.Context, arg GetSMSTemplateParams) (SmsTemplate, error) {
	row := q.db.QueryRow(ctx, getSMSTemplate, arg.ID, arg.CompanyID)
	var i SmsTemplate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Body,
		&i.MergeFields,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoterByPhone = `-- name: GetVoterByPhone :one
SELECT id, company_id FROM voters WHERE phone = $1 AND company_id = $2
`

type GetVoterByPhoneParams struct {
	Phone     string    `json:"phone"`
	CompanyID uuid.UUID `json:"company_id"`
}

type GetVoterByPhoneRow struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetVoterByPhone(ctx context.Context, arg GetVoterByPhoneParams) (GetVoterByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getVoterByPhone, arg.Phone, arg.CompanyID)
	var i GetVoterByPhoneRow
	err := row.Scan(&i.ID, &i.CompanyID)
	return i, err
}

const getVoterPhone = `-- name: GetVoterPhone :one
SELECT phone FROM voters WHERE id = $1 AND company_id = $2
`

type GetVoterPhoneParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetVoterPhone(ctx context.Context, arg GetVoterPhoneParams) (string, error) {
	row := q.db.QueryRow(ctx, getVoterPhone, arg.ID, arg.CompanyID)
	var phone string
	err := row.Scan(&phone)
	return phone, err
}

const incrementCampaignDeliveredCount = `-- name: IncrementCampaignDeliveredCount :exec
UPDATE sms_campaigns SET delivered_count = delivered_count + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementCampaignDeliveredCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementCampaignDeliveredCount, id)
	return err
}

const incrementCampaignFailedCount = `-- name: IncrementCampaignFailedCount :exec
UPDATE sms_campaigns SET failed_count = failed_count + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementCampaignFailedCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementCampaignFailedCount, id)
	return err
}

const incrementCampaignSentCount = `-- name: IncrementCampaignSentCount :exec
UPDATE sms_campaigns SET sent_count = sent_count + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementCampaignSentCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementCampaignSentCount, id)
	return err
}

const insertContactLog = `-- name: InsertContactLog :exec
INSERT INTO contact_logs (company_id, voter_id, user_id, contact_type, notes)
VALUES ($1, $2, $3, $4, $5)
`

type InsertContactLogParams struct {
	CompanyID   uuid.UUID `json:"company_id"`
	VoterID     uuid.UUID `json:"voter_id"`
	UserID      uuid.UUID `json:"user_id"`
	ContactType string    `json:"contact_type"`
	Notes       string    `json:"notes"`
}

func (q *Queries) InsertContactLog(ctx context.Context, arg InsertContactLogParams) error {
	_, err := q.db.Exec(ctx, insertContactLog,
		arg.CompanyID,
		arg.VoterID,
		arg.UserID,
		arg.ContactType,
		arg.Notes,
	)
	return err
}

const insertSMSMessage = `-- name: InsertSMSMessage :one
INSERT INTO sms_messages (company_id, voter_id, user_id, campaign_id, direction, message_type, from_number, to_number, body, twilio_message_sid, status, segments)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, created_at
`

type InsertSMSMessageParams struct {
	CompanyID        uuid.UUID   `json:"company_id"`
	VoterID          uuid.UUID   `json:"voter_id"`
	UserID           pgtype.UUID `json:"user_id"`
	CampaignID       pgtype.UUID `json:"campaign_id"`
	Direction        string      `json:"direction"`
	MessageType      string      `json:"message_type"`
	FromNumber       string      `json:"from_number"`
	ToNumber         string      `json:"to_number"`
	Body             string      `json:"body"`
	TwilioMessageSid *string     `json:"twilio_message_sid"`
	Status           string      `json:"status"`
	Segments         int32       `json:"segments"`
}

type InsertSMSMessageRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertSMSMessage(ctx context.Context, arg InsertSMSMessageParams) (InsertSMSMessageRow, error) {
	row := q.db.QueryRow(ctx, insertSMSMessage,
		arg.CompanyID,
		arg.VoterID,
		arg.UserID,
		arg.CampaignID,
		arg.Direction,
		arg.MessageType,
		arg.FromNumber,
		arg.ToNumber,
		arg.Body,
		arg.TwilioMessageSid,
		arg.Status,
		arg.Segments,
	)
	var i InsertSMSMessageRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertSMSMessageIdempotent = `-- name: InsertSMSMessageIdempotent :exec
INSERT INTO sms_messages (company_id, voter_id, user_id, campaign_id, direction, message_type, from_number, to_number, body, twilio_message_sid, status, segments)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (twilio_message_sid) DO NOTHING
`

type InsertSMSMessageIdempotentParams struct {
	CompanyID        uuid.UUID   `json:"company_id"`
	VoterID          uuid.UUID   `json:"voter_id"`
	UserID           pgtype.UUID `json:"user_id"`
	CampaignID       pgtype.UUID `json:"campaign_id"`
	Direction        string      `json:"direction"`
	MessageType      string      `json:"message_type"`
	FromNumber       string      `json:"from_number"`
	ToNumber         string      `json:"to_number"`
	Body             string      `json:"body"`
	TwilioMessageSid *string     `json:"twilio_message_sid"`
	Status           string      `json:"status"`
	Segments         int32       `json:"segments"`
}

func (q *Queries) InsertSMSMessageIdempotent(ctx context.Context, arg InsertSMSMessageIdempotentParams) error {
	_, err := q.db.Exec(ctx, insertSMSMessageIdempotent,
		arg.CompanyID,
		arg.VoterID,
		arg.UserID,
		arg.CampaignID,
		arg.Direction,
		arg.MessageType,
		arg.FromNumber,
		arg.ToNumber,
		arg.Body,
		arg.TwilioMessageSid,
		arg.Status,
		arg.Segments,
	)
	return err
}

const listConversation = `-- name: ListConversation :many
SELECT id, company_id, voter_id, user_id, campaign_id, direction, message_type, from_number, to_number, body, twilio_message_sid, status, error_code, segments, created_at, updated_at FROM sms_messages
WHERE company_id = $1 AND voter_id = $2
ORDER BY created_at ASC
LIMIT $3 OFFSET $4
`

type ListConversationParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	VoterID   uuid.UUID `json:"voter_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListConversation(ctx context.Context, arg ListConversationParams) ([]SmsMessage, error) {
	rows, err := q.db.Query(ctx, listConversation,
		arg.CompanyID,
		arg.VoterID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SmsMessage{}
	for rows.Next() {
		var i SmsMessage
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.VoterID,
			&i.UserID,
			&i.CampaignID,
			&i.Direction,
			&i.MessageType,
			&i.FromNumber,
			&i.ToNumber,
			&i.Body,
			&i.TwilioMessageSid,
			&i.Status,
			&i.ErrorCode,
			&i.Segments,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationVoters = `-- name: ListConversationVoters :many
SELECT DISTINCT ON (m.voter_id)
    m.voter_id,
    v.first_name,
    v.last_name,
    m.body AS last_message_body,
    m.created_at AS last_message_at
FROM sms_messages m
JOIN voters v ON v.id = m.voter_id
WHERE m.company_id = $1
ORDER BY m.voter_id, m.created_at DESC
LIMIT $2 OFFSET $3
`

type ListConversationVotersParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListConversationVotersRow struct {
	VoterID         uuid.UUID `json:"voter_id"`
	FirstName       string    `json:"first_name"`
	LastName        string    `json:"last_name"`
	LastMessageBody string    `json:"last_message_body"`
	LastMessageAt   time.Time `json:"last_message_at"`
}

func (q *Queries) ListConversationVoters(ctx context.Context, arg ListConversationVotersParams) ([]ListConversationVotersRow, error) {
	rows, err := q.db.Query(ctx, listConversationVoters, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationVotersRow{}
	for rows.Next() {
		var i ListConversationVotersRow
		if err := rows.Scan(
			&i.VoterID,
			&i.FirstName,
			&i.LastName,
			&i.LastMessageBody,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSMSCampaigns = `-- name: ListSMSCampaigns :many
SELECT id, company_id, name, template_id, segment_filters, status, total_recipients, sent_count, delivered_count, failed_count, created_by, launched_at, completed_at, created_at, updated_at FROM sms_campaigns
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSMSCampaignsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListSMSCampaigns(ctx context.Context, arg ListSMSCampaignsParams) ([]SmsCampaign, error) {
	rows, err := q.db.Query(ctx, listSMSCampaigns, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SmsCampaign{}
	for rows.Next() {
		var i SmsCampaign
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.TemplateID,
			&i.SegmentFilters,
			&i.Status,
			&i.TotalRecipients,
			&i.SentCount,
			&i.DeliveredCount,
			&i.FailedCount,
			&i.CreatedBy,
			&i.LaunchedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSMSTemplates = `-- name: ListSMSTemplates :many
SELECT id, company_id, name, body, merge_fields, created_by, is_active, created_at, updated_at FROM sms_templates
WHERE company_id = $1 AND is_active = true
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListSMSTemplatesParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListSMSTemplates(ctx context.Context, arg ListSMSTemplatesParams) ([]SmsTemplate, error) {
	rows, err := q.db.Query(ctx, listSMSTemplates, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SmsTemplate{}
	for rows.Next() {
		var i SmsTemplate
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Body,
			&i.MergeFields,
			&i.CreatedBy,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :exec
UPDATE sms_campaigns
SET status = $3,
    launched_at = CASE WHEN $3 = 'sending' AND launched_at IS NULL THEN now() ELSE launched_at END,
    completed_at = CASE WHEN $3 IN ('completed', 'cancelled') THEN now() ELSE completed_at END,
    updated_at = now()
WHERE id = $1 AND company_id = $2
`

type UpdateCampaignStatusParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	Status    string    `json:"status"`
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) error {
	_, err := q.db.Exec(ctx, updateCampaignStatus, arg.ID, arg.CompanyID, arg.Status)
	return err
}

const updateSMSMessageStatus = `-- name: UpdateSMSMessageStatus :exec
UPDATE sms_messages
SET status = $2, error_code = $3, updated_at = now()
WHERE twilio_message_sid = $1
`

type UpdateSMSMessageStatusParams struct {
	TwilioMessageSid *string `json:"twilio_message_sid"`
	Status           string  `json:"status"`
	ErrorCode        string  `json:"error_code"`
}

func (q *Queries) UpdateSMSMessageStatus(ctx context.Context, arg UpdateSMSMessageStatusParams) error {
	_, err := q.db.Exec(ctx, updateSMSMessageStatus, arg.TwilioMessageSid, arg.Status, arg.ErrorCode)
	return err
}

const updateSMSTemplate = `-- name: UpdateSMSTemplate :exec
UPDATE sms_templates
SET name = $3, body = $4, merge_fields = $5, updated_at = now()
WHERE id = $1 AND company_id = $2
`

type UpdateSMSTemplateParams struct {
	ID          uuid.UUID `json:"id"`
	CompanyID   uuid.UUID `json:"company_id"`
	Name        string    `json:"name"`
	Body        string    `json:"body"`
	MergeFields []string  `json:"merge_fields"`
}

func (q *Queries) UpdateSMSTemplate(ctx context.Context, arg UpdateSMSTemplateParams) error {
	_, err := q.db.Exec(ctx, updateSMSTemplate,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.Body,
		arg.MergeFields,
	)
	return err
}

const upsertSMSConfig = `-- name: UpsertSMSConfig :exec
INSERT INTO sms_config (company_id, twilio_account_sid, twilio_auth_token_encrypted, p2p_messaging_service_sid, a2p_messaging_service_sid, inbound_webhook_url, status_webhook_url, quiet_hours_start, quiet_hours_end, ten_dlc_brand_sid, ten_dlc_campaign_sid, ten_dlc_status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (company_id) DO UPDATE SET
    twilio_account_sid = EXCLUDED.twilio_account_sid,
    twilio_auth_token_encrypted = EXCLUDED.twilio_auth_token_encrypted,
    p2p_messaging_service_sid = EXCLUDED.p2p_messaging_service_sid,
    a2p_messaging_service_sid = EXCLUDED.a2p_messaging_service_sid,
    inbound_webhook_url = EXCLUDED.inbound_webhook_url,
    status_webhook_url = EXCLUDED.status_webhook_url,
    quiet_hours_start = EXCLUDED.quiet_hours_start,
    quiet_hours_end = EXCLUDED.quiet_hours_end,
    ten_dlc_brand_sid = EXCLUDED.ten_dlc_brand_sid,
    ten_dlc_campaign_sid = EXCLUDED.ten_dlc_campaign_sid,
    ten_dlc_status = EXCLUDED.ten_dlc_status,
    updated_at = now()
`

type UpsertSMSConfigParams struct {
	CompanyID                uuid.UUID `json:"company_id"`
	TwilioAccountSid         string    `json:"twilio_account_sid"`
	TwilioAuthTokenEncrypted string    `json:"twilio_auth_token_encrypted"`
	P2pMessagingServiceSid   string    `json:"p2p_messaging_service_sid"`
	A2pMessagingServiceSid   string    `json:"a2p_messaging_service_sid"`
	InboundWebhookUrl        string    `json:"inbound_webhook_url"`
	StatusWebhookUrl         string    `json:"status_webhook_url"`
	QuietHoursStart          int32     `json:"quiet_hours_start"`
	QuietHoursEnd            int32     `json:"quiet_hours_end"`
	TenDlcBrandSid           string    `json:"ten_dlc_brand_sid"`
	TenDlcCampaignSid        string    `json:"ten_dlc_campaign_sid"`
	TenDlcStatus             string    `json:"ten_dlc_status"`
}

func (q *Queries) UpsertSMSConfig(ctx context.Context, arg UpsertSMSConfigParams) error {
	_, err := q.db.Exec(ctx, upsertSMSConfig,
		arg.CompanyID,
		arg.TwilioAccountSid,
		arg.TwilioAuthTokenEncrypted,
		arg.P2pMessagingServiceSid,
		arg.A2pMessagingServiceSid,
		arg.InboundWebhookUrl,
		arg.StatusWebhookUrl,
		arg.QuietHoursStart,
		arg.QuietHoursEnd,
		arg.TenDlcBrandSid,
		arg.TenDlcCampaignSid,
		arg.TenDlcStatus,
	)
	return err
}
