// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suppression.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addToSuppressionList = `-- name: AddToSuppressionList :exec
INSERT INTO suppression_list (company_id, voter_id, reason, added_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (company_id, voter_id) DO UPDATE SET
    reason = EXCLUDED.reason,
    added_by = EXCLUDED.added_by,
    added_at = now()
`

type AddToSuppressionListParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	VoterID   uuid.UUID `json:"voter_id"`
	Reason    string    `json:"reason"`
	AddedBy   uuid.UUID `json:"added_by"`
}

func (q *Queries) AddToSuppressionList(ctx context.Context, arg AddToSuppressionListParams) error {
	_, err := q.db.Exec(ctx, addToSuppressionList,
		arg.CompanyID,
		arg.VoterID,
		arg.Reason,
		arg.AddedBy,
	)
	return err
}

const countSuppressedVoters = `-- name: CountSuppressedVoters :one
SELECT COUNT(*) FROM suppression_list WHERE company_id = $1
`

func (q *Queries) CountSuppressedVoters(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppressedVoters, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isVoterSuppressed = `-- name: IsVoterSuppressed :one
SELECT EXISTS(
    SELECT 1 FROM suppression_list WHERE company_id = $1 AND voter_id = $2
) AS is_suppressed
`

type IsVoterSuppressedParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	VoterID   uuid.UUID `json:"voter_id"`
}

func (q *Queries) IsVoterSuppressed(ctx context.Context, arg IsVoterSuppressedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isVoterSuppressed, arg.CompanyID, arg.VoterID)
	var is_suppressed bool
	err := row.Scan(&is_suppressed)
	return is_suppressed, err
}

const listSuppressedVoters = `-- name: ListSuppressedVoters :many
SELECT s.id, s.voter_id, s.reason, s.added_by, s.added_at,
       v.first_name, v.last_name, v.res_street_address, v.res_city, v.res_state, v.res_zip
FROM suppression_list s
JOIN voters v ON v.id = s.voter_id
WHERE s.company_id = $1
ORDER BY s.added_at DESC
LIMIT $2 OFFSET $3
`

type ListSuppressedVotersParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListSuppressedVotersRow struct {
	ID               uuid.UUID `json:"id"`
	VoterID          uuid.UUID `json:"voter_id"`
	Reason           string    `json:"reason"`
	AddedBy          uuid.UUID `json:"added_by"`
	AddedAt          time.Time `json:"added_at"`
	FirstName        string    `json:"first_name"`
	LastName         string    `json:"last_name"`
	ResStreetAddress string    `json:"res_street_address"`
	ResCity          string    `json:"res_city"`
	ResState         string    `json:"res_state"`
	ResZip           string    `json:"res_zip"`
}

func (q *Queries) ListSuppressedVoters(ctx context.Context, arg ListSuppressedVotersParams) ([]ListSuppressedVotersRow, error) {
	rows, err := q.db.Query(ctx, listSuppressedVoters, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSuppressedVotersRow{}
	for rows.Next() {
		var i ListSuppressedVotersRow
		if err := rows.Scan(
			&i.ID,
			&i.VoterID,
			&i.Reason,
			&i.AddedBy,
			&i.AddedAt,
			&i.FirstName,
			&i.LastName,
			&i.ResStreetAddress,
			&i.ResCity,
			&i.ResState,
			&i.ResZip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFromSuppressionList = `-- name: RemoveFromSuppressionList :exec
DELETE FROM suppression_list
WHERE company_id = $1 AND voter_id = $2
`

type RemoveFromSuppressionListParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	VoterID   uuid.UUID `json:"voter_id"`
}

func (q *Queries) RemoveFromSuppressionList(ctx context.Context, arg RemoveFromSuppressionListParams) error {
	_, err := q.db.Exec(ctx, removeFromSuppressionList, arg.CompanyID, arg.VoterID)
	return err
}
