// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: surveys.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSurveyForm = `-- name: CreateSurveyForm :one
INSERT INTO survey_forms (company_id, title, description, schema, version, is_active, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, title, description, schema, version, is_active, created_by, created_at, updated_at
`

type CreateSurveyFormParams struct {
	CompanyID   uuid.UUID       `json:"company_id"`
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Schema      json.RawMessage `json:"schema"`
	Version     int32           `json:"version"`
	IsActive    bool            `json:"is_active"`
	CreatedBy   uuid.UUID       `json:"created_by"`
}

// Create a new survey form.
func (q *Queries) CreateSurveyForm(ctx context.Context, arg CreateSurveyFormParams) (SurveyForm, error) {
	row := q.db.QueryRow(ctx, createSurveyForm,
		arg.CompanyID,
		arg.Title,
		arg.Description,
		arg.Schema,
		arg.Version,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i SurveyForm
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Schema,
		&i.Version,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSurveyForm = `-- name: GetSurveyForm :one
SELECT id, company_id, title, description, schema, version, is_active, created_by, created_at, updated_at FROM survey_forms
WHERE id = $1 AND company_id = $2
`

type GetSurveyFormParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

// Get a survey form by ID and company.
func (q *Queries) GetSurveyForm(ctx context.Context, arg GetSurveyFormParams) (SurveyForm, error) {
	row := q.db.QueryRow(ctx, getSurveyForm, arg.ID, arg.CompanyID)
	var i SurveyForm
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Schema,
		&i.Version,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSurveyResponsesForVoter = `-- name: GetSurveyResponsesForVoter :many
SELECT id, company_id, form_id, form_version, voter_id, user_id, turf_id, contact_log_id, responses, created_at FROM survey_responses
WHERE voter_id = $1 AND company_id = $2
ORDER BY created_at DESC
`

type GetSurveyResponsesForVoterParams struct {
	VoterID   uuid.UUID `json:"voter_id"`
	CompanyID uuid.UUID `json:"company_id"`
}

// Get survey responses for a voter.
func (q *Queries) GetSurveyResponsesForVoter(ctx context.Context, arg GetSurveyResponsesForVoterParams) ([]SurveyResponse, error) {
	rows, err := q.db.Query(ctx, getSurveyResponsesForVoter, arg.VoterID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SurveyResponse{}
	for rows.Next() {
		var i SurveyResponse
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FormID,
			&i.FormVersion,
			&i.VoterID,
			&i.UserID,
			&i.TurfID,
			&i.ContactLogID,
			&i.Responses,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSurveyForms = `-- name: ListActiveSurveyForms :many
SELECT id, company_id, title, description, schema, version, is_active, created_by, created_at, updated_at FROM survey_forms
WHERE company_id = $1 AND is_active = true
ORDER BY created_at DESC
`

// List active survey forms for a company.
func (q *Queries) ListActiveSurveyForms(ctx context.Context, companyID uuid.UUID) ([]SurveyForm, error) {
	rows, err := q.db.Query(ctx, listActiveSurveyForms, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SurveyForm{}
	for rows.Next() {
		var i SurveyForm
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.Schema,
			&i.Version,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSurveyForm = `-- name: UpdateSurveyForm :exec
UPDATE survey_forms
SET title = $3, description = $4, schema = $5, version = $6, is_active = $7, updated_at = now()
WHERE id = $1 AND company_id = $2
`

type UpdateSurveyFormParams struct {
	ID          uuid.UUID       `json:"id"`
	CompanyID   uuid.UUID       `json:"company_id"`
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Schema      json.RawMessage `json:"schema"`
	Version     int32           `json:"version"`
	IsActive    bool            `json:"is_active"`
}

// Update survey form fields.
func (q *Queries) UpdateSurveyForm(ctx context.Context, arg UpdateSurveyFormParams) error {
	_, err := q.db.Exec(ctx, updateSurveyForm,
		arg.ID,
		arg.CompanyID,
		arg.Title,
		arg.Description,
		arg.Schema,
		arg.Version,
		arg.IsActive,
	)
	return err
}

const upsertSurveyResponseFromSync = `-- name: UpsertSurveyResponseFromSync :exec
INSERT INTO survey_responses (id, company_id, form_id, form_version, voter_id, user_id, turf_id, contact_log_id, responses, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO NOTHING
`

type UpsertSurveyResponseFromSyncParams struct {
	ID           uuid.UUID       `json:"id"`
	CompanyID    uuid.UUID       `json:"company_id"`
	FormID       uuid.UUID       `json:"form_id"`
	FormVersion  int32           `json:"form_version"`
	VoterID      uuid.UUID       `json:"voter_id"`
	UserID       uuid.UUID       `json:"user_id"`
	TurfID       pgtype.UUID     `json:"turf_id"`
	ContactLogID pgtype.UUID     `json:"contact_log_id"`
	Responses    json.RawMessage `json:"responses"`
	CreatedAt    time.Time       `json:"created_at"`
}

// Insert a survey response from a client sync push. Append-only: skip if already exists.
func (q *Queries) UpsertSurveyResponseFromSync(ctx context.Context, arg UpsertSurveyResponseFromSyncParams) error {
	_, err := q.db.Exec(ctx, upsertSurveyResponseFromSync,
		arg.ID,
		arg.CompanyID,
		arg.FormID,
		arg.FormVersion,
		arg.VoterID,
		arg.UserID,
		arg.TurfID,
		arg.ContactLogID,
		arg.Responses,
		arg.CreatedAt,
	)
	return err
}
