// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getSyncServerCursor = `-- name: GetSyncServerCursor :one
SELECT last_cursor FROM sync_server_cursors
WHERE user_id = $1 AND entity_type = $2
`

type GetSyncServerCursorParams struct {
	UserID     uuid.UUID `json:"user_id"`
	EntityType string    `json:"entity_type"`
}

func (q *Queries) GetSyncServerCursor(ctx context.Context, arg GetSyncServerCursorParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, getSyncServerCursor, arg.UserID, arg.EntityType)
	var last_cursor time.Time
	err := row.Scan(&last_cursor)
	return last_cursor, err
}

const getSyncTurfAssignments = `-- name: GetSyncTurfAssignments :many
SELECT
    t.id as turf_id,
    t.name as turf_name,
    ST_AsGeoJSON(t.boundary) as boundary_geojson,
    (SELECT COUNT(*) FROM voters v
     WHERE v.company_id = t.company_id
       AND v.location IS NOT NULL
       AND v.geocode_status = 'success'
       AND ST_Contains(t.boundary, v.location))::bigint as voter_count
FROM turf_assignments ta
JOIN turfs t ON t.id = ta.turf_id
WHERE ta.user_id = $1
  AND t.is_active = true
`

type GetSyncTurfAssignmentsRow struct {
	TurfID          uuid.UUID   `json:"turf_id"`
	TurfName        string      `json:"turf_name"`
	BoundaryGeojson interface{} `json:"boundary_geojson"`
	VoterCount      int64       `json:"voter_count"`
}

// Returns turf info with boundary and voter count for a user's assigned turfs.
func (q *Queries) GetSyncTurfAssignments(ctx context.Context, userID uuid.UUID) ([]GetSyncTurfAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, getSyncTurfAssignments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSyncTurfAssignmentsRow{}
	for rows.Next() {
		var i GetSyncTurfAssignmentsRow
		if err := rows.Scan(
			&i.TurfID,
			&i.TurfName,
			&i.BoundaryGeojson,
			&i.VoterCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSyncServerCursor = `-- name: UpsertSyncServerCursor :exec
INSERT INTO sync_server_cursors (user_id, entity_type, last_cursor)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, entity_type) DO UPDATE
SET last_cursor = EXCLUDED.last_cursor
`

type UpsertSyncServerCursorParams struct {
	UserID     uuid.UUID `json:"user_id"`
	EntityType string    `json:"entity_type"`
	LastCursor time.Time `json:"last_cursor"`
}

func (q *Queries) UpsertSyncServerCursor(ctx context.Context, arg UpsertSyncServerCursorParams) error {
	_, err := q.db.Exec(ctx, upsertSyncServerCursor, arg.UserID, arg.EntityType, arg.LastCursor)
	return err
}
