// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkSyncOperationProcessed = `-- name: CheckSyncOperationProcessed :one
SELECT EXISTS(
  SELECT 1 FROM sync_received_operations
  WHERE client_operation_id = $1 AND company_id = $2
)
`

type CheckSyncOperationProcessedParams struct {
	ClientOperationID string    `json:"client_operation_id"`
	CompanyID         uuid.UUID `json:"company_id"`
}

// Check if a client sync operation has already been processed (idempotency).
func (q *Queries) CheckSyncOperationProcessed(ctx context.Context, arg CheckSyncOperationProcessedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkSyncOperationProcessed, arg.ClientOperationID, arg.CompanyID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getSyncServerCursor = `-- name: GetSyncServerCursor :one
SELECT last_cursor FROM sync_server_cursors
WHERE user_id = $1 AND entity_type = $2
`

type GetSyncServerCursorParams struct {
	UserID     uuid.UUID `json:"user_id"`
	EntityType string    `json:"entity_type"`
}

func (q *Queries) GetSyncServerCursor(ctx context.Context, arg GetSyncServerCursorParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, getSyncServerCursor, arg.UserID, arg.EntityType)
	var last_cursor time.Time
	err := row.Scan(&last_cursor)
	return last_cursor, err
}

const getSyncTurfAssignments = `-- name: GetSyncTurfAssignments :many
SELECT
    t.id as turf_id,
    t.name as turf_name,
    ST_AsGeoJSON(t.boundary) as boundary_geojson,
    (SELECT COUNT(*) FROM voters v
     WHERE v.company_id = t.company_id
       AND v.location IS NOT NULL
       AND v.geocode_status = 'success'
       AND ST_Contains(t.boundary, v.location))::bigint as voter_count
FROM turf_assignments ta
JOIN turfs t ON t.id = ta.turf_id
WHERE ta.user_id = $1
  AND t.is_active = true
`

type GetSyncTurfAssignmentsRow struct {
	TurfID          uuid.UUID   `json:"turf_id"`
	TurfName        string      `json:"turf_name"`
	BoundaryGeojson interface{} `json:"boundary_geojson"`
	VoterCount      int64       `json:"voter_count"`
}

// Returns turf info with boundary and voter count for a user's assigned turfs.
func (q *Queries) GetSyncTurfAssignments(ctx context.Context, userID uuid.UUID) ([]GetSyncTurfAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, getSyncTurfAssignments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSyncTurfAssignmentsRow{}
	for rows.Next() {
		var i GetSyncTurfAssignmentsRow
		if err := rows.Scan(
			&i.TurfID,
			&i.TurfName,
			&i.BoundaryGeojson,
			&i.VoterCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pullSurveyForms = `-- name: PullSurveyForms :many
SELECT id, company_id, title, description, schema, version, is_active, created_by, created_at, updated_at
FROM survey_forms
WHERE company_id = $1 AND is_active = true AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type PullSurveyFormsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

// Pull active survey forms updated since cursor.
func (q *Queries) PullSurveyForms(ctx context.Context, arg PullSurveyFormsParams) ([]SurveyForm, error) {
	rows, err := q.db.Query(ctx, pullSurveyForms, arg.CompanyID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SurveyForm{}
	for rows.Next() {
		var i SurveyForm
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.Schema,
			&i.Version,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pullSurveyResponses = `-- name: PullSurveyResponses :many
SELECT id, company_id, form_id, form_version, voter_id, user_id, turf_id, contact_log_id, responses, created_at
FROM survey_responses
WHERE company_id = $1 AND turf_id = ANY($2::uuid[]) AND created_at > $3
ORDER BY created_at ASC
LIMIT $4
`

type PullSurveyResponsesParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	Column2   []uuid.UUID `json:"column_2"`
	CreatedAt time.Time   `json:"created_at"`
	Limit     int32       `json:"limit"`
}

// Pull survey responses created since cursor, scoped to turfs.
func (q *Queries) PullSurveyResponses(ctx context.Context, arg PullSurveyResponsesParams) ([]SurveyResponse, error) {
	rows, err := q.db.Query(ctx, pullSurveyResponses,
		arg.CompanyID,
		arg.Column2,
		arg.CreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SurveyResponse{}
	for rows.Next() {
		var i SurveyResponse
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FormID,
			&i.FormVersion,
			&i.VoterID,
			&i.UserID,
			&i.TurfID,
			&i.ContactLogID,
			&i.Responses,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSyncOperationProcessed = `-- name: RecordSyncOperationProcessed :exec
INSERT INTO sync_received_operations (client_operation_id, user_id, company_id, entity_type, entity_id, operation_type)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT DO NOTHING
`

type RecordSyncOperationProcessedParams struct {
	ClientOperationID string    `json:"client_operation_id"`
	UserID            uuid.UUID `json:"user_id"`
	CompanyID         uuid.UUID `json:"company_id"`
	EntityType        string    `json:"entity_type"`
	EntityID          string    `json:"entity_id"`
	OperationType     string    `json:"operation_type"`
}

// Record a processed sync operation for idempotency tracking.
func (q *Queries) RecordSyncOperationProcessed(ctx context.Context, arg RecordSyncOperationProcessedParams) error {
	_, err := q.db.Exec(ctx, recordSyncOperationProcessed,
		arg.ClientOperationID,
		arg.UserID,
		arg.CompanyID,
		arg.EntityType,
		arg.EntityID,
		arg.OperationType,
	)
	return err
}

const updateVoterUpdatedAtFromSync = `-- name: UpdateVoterUpdatedAtFromSync :exec
UPDATE voters
SET updated_at = now()
WHERE id = $1 AND company_id = $2
  AND updated_at < $3
`

type UpdateVoterUpdatedAtFromSyncParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Update voter updated_at timestamp from a client sync push using LWW (last-write-wins).
// Only updates if the client's timestamp is newer than the server's current updated_at.
// Actual field updates are handled in Go code via raw pgxpool for flexibility.
func (q *Queries) UpdateVoterUpdatedAtFromSync(ctx context.Context, arg UpdateVoterUpdatedAtFromSyncParams) error {
	_, err := q.db.Exec(ctx, updateVoterUpdatedAtFromSync, arg.ID, arg.CompanyID, arg.UpdatedAt)
	return err
}

const upsertContactLogFromSync = `-- name: UpsertContactLogFromSync :exec
INSERT INTO contact_logs (id, company_id, voter_id, user_id, turf_id, contact_type, outcome, notes, door_status, sentiment, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO NOTHING
`

type UpsertContactLogFromSyncParams struct {
	ID          uuid.UUID   `json:"id"`
	CompanyID   uuid.UUID   `json:"company_id"`
	VoterID     uuid.UUID   `json:"voter_id"`
	UserID      uuid.UUID   `json:"user_id"`
	TurfID      pgtype.UUID `json:"turf_id"`
	ContactType string      `json:"contact_type"`
	Outcome     string      `json:"outcome"`
	Notes       string      `json:"notes"`
	DoorStatus  string      `json:"door_status"`
	Sentiment   *int32      `json:"sentiment"`
	CreatedAt   time.Time   `json:"created_at"`
}

// Insert a contact log from a client sync push. Append-only: skip if already exists.
func (q *Queries) UpsertContactLogFromSync(ctx context.Context, arg UpsertContactLogFromSyncParams) error {
	_, err := q.db.Exec(ctx, upsertContactLogFromSync,
		arg.ID,
		arg.CompanyID,
		arg.VoterID,
		arg.UserID,
		arg.TurfID,
		arg.ContactType,
		arg.Outcome,
		arg.Notes,
		arg.DoorStatus,
		arg.Sentiment,
		arg.CreatedAt,
	)
	return err
}

const upsertSyncServerCursor = `-- name: UpsertSyncServerCursor :exec
INSERT INTO sync_server_cursors (user_id, entity_type, last_cursor)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, entity_type) DO UPDATE
SET last_cursor = EXCLUDED.last_cursor
`

type UpsertSyncServerCursorParams struct {
	UserID     uuid.UUID `json:"user_id"`
	EntityType string    `json:"entity_type"`
	LastCursor time.Time `json:"last_cursor"`
}

func (q *Queries) UpsertSyncServerCursor(ctx context.Context, arg UpsertSyncServerCursorParams) error {
	_, err := q.db.Exec(ctx, upsertSyncServerCursor, arg.UserID, arg.EntityType, arg.LastCursor)
	return err
}
