// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const assignTagToVoter = `-- name: AssignTagToVoter :exec
INSERT INTO voter_tag_assignments (voter_id, tag_id, assigned_by)
VALUES ($1, $2, $3)
ON CONFLICT (voter_id, tag_id) DO NOTHING
`

type AssignTagToVoterParams struct {
	VoterID    uuid.UUID `json:"voter_id"`
	TagID      uuid.UUID `json:"tag_id"`
	AssignedBy uuid.UUID `json:"assigned_by"`
}

func (q *Queries) AssignTagToVoter(ctx context.Context, arg AssignTagToVoterParams) error {
	_, err := q.db.Exec(ctx, assignTagToVoter, arg.VoterID, arg.TagID, arg.AssignedBy)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO voter_tags (company_id, name, color, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, company_id, name, color, created_by, created_at
`

type CreateTagParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Name      string    `json:"name"`
	Color     string    `json:"color"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (VoterTag, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.CompanyID,
		arg.Name,
		arg.Color,
		arg.CreatedBy,
	)
	var i VoterTag
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Color,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM voter_tags WHERE id = $1 AND company_id = $2
`

type DeleteTagParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.CompanyID)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, company_id, name, color, created_by, created_at FROM voter_tags WHERE id = $1
`

func (q *Queries) GetTag(ctx context.Context, id uuid.UUID) (VoterTag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i VoterTag
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Color,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getVoterTags = `-- name: GetVoterTags :many
SELECT vt.id, vt.company_id, vt.name, vt.color, vt.created_by, vt.created_at FROM voter_tags vt
JOIN voter_tag_assignments vta ON vta.tag_id = vt.id
WHERE vta.voter_id = $1
ORDER BY vt.name
`

func (q *Queries) GetVoterTags(ctx context.Context, voterID uuid.UUID) ([]VoterTag, error) {
	rows, err := q.db.Query(ctx, getVoterTags, voterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoterTag{}
	for rows.Next() {
		var i VoterTag
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Color,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, company_id, name, color, created_by, created_at FROM voter_tags
WHERE company_id = $1
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context, companyID uuid.UUID) ([]VoterTag, error) {
	rows, err := q.db.Query(ctx, listTags, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoterTag{}
	for rows.Next() {
		var i VoterTag
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Color,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVotersByTag = `-- name: ListVotersByTag :many
SELECT v.id, v.first_name, v.last_name, v.party, v.status,
       v.res_city, v.res_zip, v.municipality, v.year_of_birth
FROM voters v
JOIN voter_tag_assignments vta ON vta.voter_id = v.id
WHERE vta.tag_id = $1 AND v.company_id = $2
ORDER BY v.last_name, v.first_name
LIMIT $3 OFFSET $4
`

type ListVotersByTagParams struct {
	TagID     uuid.UUID `json:"tag_id"`
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListVotersByTagRow struct {
	ID           uuid.UUID `json:"id"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	Party        string    `json:"party"`
	Status       string    `json:"status"`
	ResCity      string    `json:"res_city"`
	ResZip       string    `json:"res_zip"`
	Municipality string    `json:"municipality"`
	YearOfBirth  *int32    `json:"year_of_birth"`
}

func (q *Queries) ListVotersByTag(ctx context.Context, arg ListVotersByTagParams) ([]ListVotersByTagRow, error) {
	rows, err := q.db.Query(ctx, listVotersByTag,
		arg.TagID,
		arg.CompanyID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVotersByTagRow{}
	for rows.Next() {
		var i ListVotersByTagRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Party,
			&i.Status,
			&i.ResCity,
			&i.ResZip,
			&i.Municipality,
			&i.YearOfBirth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromVoter = `-- name: RemoveTagFromVoter :exec
DELETE FROM voter_tag_assignments
WHERE voter_id = $1 AND tag_id = $2
`

type RemoveTagFromVoterParams struct {
	VoterID uuid.UUID `json:"voter_id"`
	TagID   uuid.UUID `json:"tag_id"`
}

func (q *Queries) RemoveTagFromVoter(ctx context.Context, arg RemoveTagFromVoterParams) error {
	_, err := q.db.Exec(ctx, removeTagFromVoter, arg.VoterID, arg.TagID)
	return err
}
