// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (company_id, title, description, task_type, priority, status, due_date, linked_entity_type, linked_entity_id, total_count, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, company_id, title, description, task_type, priority, status, due_date, linked_entity_type, linked_entity_id, progress_pct, total_count, completed_count, created_by, created_at, updated_at
`

type CreateTaskParams struct {
	CompanyID        uuid.UUID          `json:"company_id"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	TaskType         string             `json:"task_type"`
	Priority         string             `json:"priority"`
	Status           string             `json:"status"`
	DueDate          pgtype.Timestamptz `json:"due_date"`
	LinkedEntityType *string            `json:"linked_entity_type"`
	LinkedEntityID   pgtype.UUID        `json:"linked_entity_id"`
	TotalCount       int32              `json:"total_count"`
	CreatedBy        uuid.UUID          `json:"created_by"`
}

// Create a new task.
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.CompanyID,
		arg.Title,
		arg.Description,
		arg.TaskType,
		arg.Priority,
		arg.Status,
		arg.DueDate,
		arg.LinkedEntityType,
		arg.LinkedEntityID,
		arg.TotalCount,
		arg.CreatedBy,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.TaskType,
		&i.Priority,
		&i.Status,
		&i.DueDate,
		&i.LinkedEntityType,
		&i.LinkedEntityID,
		&i.ProgressPct,
		&i.TotalCount,
		&i.CompletedCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskAssignment = `-- name: CreateTaskAssignment :exec
INSERT INTO task_assignments (task_id, user_id, assigned_by)
VALUES ($1, $2, $3)
ON CONFLICT (task_id, user_id) DO NOTHING
`

type CreateTaskAssignmentParams struct {
	TaskID     uuid.UUID `json:"task_id"`
	UserID     uuid.UUID `json:"user_id"`
	AssignedBy uuid.UUID `json:"assigned_by"`
}

// Assign a user to a task.
func (q *Queries) CreateTaskAssignment(ctx context.Context, arg CreateTaskAssignmentParams) error {
	_, err := q.db.Exec(ctx, createTaskAssignment, arg.TaskID, arg.UserID, arg.AssignedBy)
	return err
}

const createTaskNote = `-- name: CreateTaskNote :one
INSERT INTO task_notes (company_id, task_id, user_id, content, visibility)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, company_id, task_id, user_id, content, visibility, created_at
`

type CreateTaskNoteParams struct {
	CompanyID  uuid.UUID `json:"company_id"`
	TaskID     uuid.UUID `json:"task_id"`
	UserID     uuid.UUID `json:"user_id"`
	Content    string    `json:"content"`
	Visibility string    `json:"visibility"`
}

// Create a task note.
func (q *Queries) CreateTaskNote(ctx context.Context, arg CreateTaskNoteParams) (TaskNote, error) {
	row := q.db.QueryRow(ctx, createTaskNote,
		arg.CompanyID,
		arg.TaskID,
		arg.UserID,
		arg.Content,
		arg.Visibility,
	)
	var i TaskNote
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.TaskID,
		&i.UserID,
		&i.Content,
		&i.Visibility,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1 AND company_id = $2
`

type DeleteTaskParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

// Delete a task by ID and company.
func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.CompanyID)
	return err
}

const deleteTaskAssignment = `-- name: DeleteTaskAssignment :exec
DELETE FROM task_assignments
WHERE task_id = $1 AND user_id = $2
`

type DeleteTaskAssignmentParams struct {
	TaskID uuid.UUID `json:"task_id"`
	UserID uuid.UUID `json:"user_id"`
}

// Remove a user assignment from a task.
func (q *Queries) DeleteTaskAssignment(ctx context.Context, arg DeleteTaskAssignmentParams) error {
	_, err := q.db.Exec(ctx, deleteTaskAssignment, arg.TaskID, arg.UserID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, company_id, title, description, task_type, priority, status, due_date, linked_entity_type, linked_entity_id, progress_pct, total_count, completed_count, created_by, created_at, updated_at FROM tasks
WHERE id = $1 AND company_id = $2
`

type GetTaskParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

// Get a task by ID and company.
func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.CompanyID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.TaskType,
		&i.Priority,
		&i.Status,
		&i.DueDate,
		&i.LinkedEntityType,
		&i.LinkedEntityID,
		&i.ProgressPct,
		&i.TotalCount,
		&i.CompletedCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskAssigneeUserIDs = `-- name: GetTaskAssigneeUserIDs :many
SELECT user_id FROM task_assignments WHERE task_id = $1
`

// Get all assignee user IDs for a task.
func (q *Queries) GetTaskAssigneeUserIDs(ctx context.Context, taskID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getTaskAssigneeUserIDs, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskAssignments = `-- name: GetTaskAssignments :many
SELECT ta.id, ta.task_id, ta.user_id, ta.assigned_by, ta.assigned_at,
       u.display_name as user_display_name
FROM task_assignments ta
JOIN users u ON u.id = ta.user_id
WHERE ta.task_id = $1
`

type GetTaskAssignmentsRow struct {
	ID              uuid.UUID `json:"id"`
	TaskID          uuid.UUID `json:"task_id"`
	UserID          uuid.UUID `json:"user_id"`
	AssignedBy      uuid.UUID `json:"assigned_by"`
	AssignedAt      time.Time `json:"assigned_at"`
	UserDisplayName string    `json:"user_display_name"`
}

// Get all assignments for a task with user names.
func (q *Queries) GetTaskAssignments(ctx context.Context, taskID uuid.UUID) ([]GetTaskAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, getTaskAssignments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTaskAssignmentsRow{}
	for rows.Next() {
		var i GetTaskAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.UserDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskVoterCount = `-- name: GetTaskVoterCount :one
SELECT count(*) AS total, count(*) FILTER (WHERE is_contacted) AS contacted
FROM task_voters
WHERE task_id = $1
`

type GetTaskVoterCountRow struct {
	Total     int64 `json:"total"`
	Contacted int64 `json:"contacted"`
}

// Get total and contacted count for a task's voters.
func (q *Queries) GetTaskVoterCount(ctx context.Context, taskID uuid.UUID) (GetTaskVoterCountRow, error) {
	row := q.db.QueryRow(ctx, getTaskVoterCount, taskID)
	var i GetTaskVoterCountRow
	err := row.Scan(&i.Total, &i.Contacted)
	return i, err
}

const getTasksDueSoon = `-- name: GetTasksDueSoon :many
SELECT t.id, t.company_id, t.title, t.due_date, array_agg(ta.user_id)::uuid[] as assignee_ids
FROM tasks t
JOIN task_assignments ta ON ta.task_id = t.id
WHERE t.status IN ('open', 'in_progress')
  AND t.due_date IS NOT NULL
  AND t.due_date BETWEEN now() AND now() + interval '24 hours'
GROUP BY t.id
`

type GetTasksDueSoonRow struct {
	ID          uuid.UUID          `json:"id"`
	CompanyID   uuid.UUID          `json:"company_id"`
	Title       string             `json:"title"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	AssigneeIds []uuid.UUID        `json:"assignee_ids"`
}

// Get tasks with due dates within the next 24 hours, grouped with assignee IDs.
func (q *Queries) GetTasksDueSoon(ctx context.Context) ([]GetTasksDueSoonRow, error) {
	rows, err := q.db.Query(ctx, getTasksDueSoon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTasksDueSoonRow{}
	for rows.Next() {
		var i GetTasksDueSoonRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.DueDate,
			&i.AssigneeIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksLinkedToVoter = `-- name: GetTasksLinkedToVoter :many
SELECT DISTINCT t.id, t.company_id, t.title, t.description, t.task_type, t.priority, t.status, t.due_date, t.linked_entity_type, t.linked_entity_id, t.progress_pct, t.total_count, t.completed_count, t.created_by, t.created_at, t.updated_at FROM tasks t
LEFT JOIN task_voters tv ON tv.task_id = t.id AND tv.voter_id = $1
WHERE t.company_id = $2
  AND t.status IN ('open', 'in_progress')
  AND (
    tv.voter_id IS NOT NULL
    OR (t.linked_entity_type = 'voter' AND t.linked_entity_id = $1)
    OR (t.linked_entity_type = 'turf' AND t.linked_entity_id = $3)
  )
`

type GetTasksLinkedToVoterParams struct {
	VoterID   uuid.UUID   `json:"voter_id"`
	CompanyID uuid.UUID   `json:"company_id"`
	TurfID    pgtype.UUID `json:"turf_id"`
}

// Find active tasks linked to a voter (via task_voters or linked_entity).
func (q *Queries) GetTasksLinkedToVoter(ctx context.Context, arg GetTasksLinkedToVoterParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksLinkedToVoter, arg.VoterID, arg.CompanyID, arg.TurfID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.TaskType,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.LinkedEntityType,
			&i.LinkedEntityID,
			&i.ProgressPct,
			&i.TotalCount,
			&i.CompletedCount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type InsertTaskVotersParams struct {
	TaskID  uuid.UUID `json:"task_id"`
	VoterID uuid.UUID `json:"voter_id"`
}

const listTaskNotes = `-- name: ListTaskNotes :many
SELECT id, company_id, task_id, user_id, content, visibility, created_at FROM task_notes
WHERE task_id = $1
ORDER BY created_at ASC
`

// List notes for a task, ordered by created_at.
func (q *Queries) ListTaskNotes(ctx context.Context, taskID uuid.UUID) ([]TaskNote, error) {
	rows, err := q.db.Query(ctx, listTaskNotes, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskNote{}
	for rows.Next() {
		var i TaskNote
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.TaskID,
			&i.UserID,
			&i.Content,
			&i.Visibility,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByAssignee = `-- name: ListTasksByAssignee :many
SELECT t.id, t.company_id, t.title, t.description, t.task_type, t.priority, t.status, t.due_date, t.linked_entity_type, t.linked_entity_id, t.progress_pct, t.total_count, t.completed_count, t.created_by, t.created_at, t.updated_at FROM tasks t
JOIN task_assignments ta ON ta.task_id = t.id
WHERE ta.user_id = $1 AND t.company_id = $2
ORDER BY t.created_at DESC
`

type ListTasksByAssigneeParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CompanyID uuid.UUID `json:"company_id"`
}

// List tasks assigned to a specific user.
func (q *Queries) ListTasksByAssignee(ctx context.Context, arg ListTasksByAssigneeParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByAssignee, arg.UserID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.TaskType,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.LinkedEntityType,
			&i.LinkedEntityID,
			&i.ProgressPct,
			&i.TotalCount,
			&i.CompletedCount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByCompany = `-- name: ListTasksByCompany :many
SELECT id, company_id, title, description, task_type, priority, status, due_date, linked_entity_type, linked_entity_id, progress_pct, total_count, completed_count, created_by, created_at, updated_at FROM tasks
WHERE company_id = $1
ORDER BY created_at DESC
`

// List tasks for a company, ordered by created_at DESC.
func (q *Queries) ListTasksByCompany(ctx context.Context, companyID uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.TaskType,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.LinkedEntityType,
			&i.LinkedEntityID,
			&i.ProgressPct,
			&i.TotalCount,
			&i.CompletedCount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskVoterContacted = `-- name: MarkTaskVoterContacted :exec
UPDATE task_voters
SET is_contacted = true, contacted_at = now()
WHERE task_id = $1 AND voter_id = $2
`

type MarkTaskVoterContactedParams struct {
	TaskID  uuid.UUID `json:"task_id"`
	VoterID uuid.UUID `json:"voter_id"`
}

// Mark a voter as contacted on a task.
func (q *Queries) MarkTaskVoterContacted(ctx context.Context, arg MarkTaskVoterContactedParams) error {
	_, err := q.db.Exec(ctx, markTaskVoterContacted, arg.TaskID, arg.VoterID)
	return err
}

const pullTaskAssignmentsUpdated = `-- name: PullTaskAssignmentsUpdated :many
SELECT ta.id, ta.task_id, ta.user_id, ta.assigned_by, ta.assigned_at
FROM task_assignments ta
JOIN tasks t ON t.id = ta.task_id
WHERE t.company_id = $1 AND ta.assigned_at > $2
ORDER BY ta.assigned_at ASC
LIMIT $3
`

type PullTaskAssignmentsUpdatedParams struct {
	CompanyID  uuid.UUID `json:"company_id"`
	AssignedAt time.Time `json:"assigned_at"`
	Limit      int32     `json:"limit"`
}

// Pull task assignments for a company's tasks since cursor.
func (q *Queries) PullTaskAssignmentsUpdated(ctx context.Context, arg PullTaskAssignmentsUpdatedParams) ([]TaskAssignment, error) {
	rows, err := q.db.Query(ctx, pullTaskAssignmentsUpdated, arg.CompanyID, arg.AssignedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskAssignment{}
	for rows.Next() {
		var i TaskAssignment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.AssignedBy,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pullTaskNotesUpdated = `-- name: PullTaskNotesUpdated :many
SELECT id, company_id, task_id, user_id, content, visibility, created_at
FROM task_notes
WHERE company_id = $1 AND created_at > $2
ORDER BY created_at ASC
LIMIT $3
`

type PullTaskNotesUpdatedParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	CreatedAt time.Time `json:"created_at"`
	Limit     int32     `json:"limit"`
}

// Pull task notes updated since cursor for sync.
func (q *Queries) PullTaskNotesUpdated(ctx context.Context, arg PullTaskNotesUpdatedParams) ([]TaskNote, error) {
	rows, err := q.db.Query(ctx, pullTaskNotesUpdated, arg.CompanyID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskNote{}
	for rows.Next() {
		var i TaskNote
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.TaskID,
			&i.UserID,
			&i.Content,
			&i.Visibility,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pullTasksUpdated = `-- name: PullTasksUpdated :many
SELECT id, company_id, title, description, task_type, priority, status,
       due_date, linked_entity_type, linked_entity_id,
       progress_pct, total_count, completed_count,
       created_by, created_at, updated_at
FROM tasks
WHERE company_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type PullTasksUpdatedParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

// Pull tasks updated since cursor for sync.
func (q *Queries) PullTasksUpdated(ctx context.Context, arg PullTasksUpdatedParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, pullTasksUpdated, arg.CompanyID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.TaskType,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.LinkedEntityType,
			&i.LinkedEntityID,
			&i.ProgressPct,
			&i.TotalCount,
			&i.CompletedCount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recalculateTaskProgress = `-- name: RecalculateTaskProgress :exec
UPDATE tasks SET
    completed_count = sub.contacted,
    progress_pct = CASE WHEN sub.total = 0 THEN 0 ELSE (sub.contacted * 100 / sub.total) END,
    status = CASE WHEN sub.contacted >= sub.total AND sub.total > 0 THEN 'completed' ELSE status END,
    updated_at = now()
FROM (
    SELECT task_id, count(*)::int AS total, count(*) FILTER (WHERE is_contacted)::int AS contacted
    FROM task_voters WHERE task_id = $1 GROUP BY task_id
) sub
WHERE tasks.id = sub.task_id AND tasks.id = $1
`

// Recalculate task progress from task_voters counts.
func (q *Queries) RecalculateTaskProgress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recalculateTaskProgress, id)
	return err
}

const updateTaskProgress = `-- name: UpdateTaskProgress :exec
UPDATE tasks
SET progress_pct = $3, completed_count = $4, updated_at = now()
WHERE id = $1 AND company_id = $2
`

type UpdateTaskProgressParams struct {
	ID             uuid.UUID `json:"id"`
	CompanyID      uuid.UUID `json:"company_id"`
	ProgressPct    int32     `json:"progress_pct"`
	CompletedCount int32     `json:"completed_count"`
}

// Update a task's progress percentage and completed count.
func (q *Queries) UpdateTaskProgress(ctx context.Context, arg UpdateTaskProgressParams) error {
	_, err := q.db.Exec(ctx, updateTaskProgress,
		arg.ID,
		arg.CompanyID,
		arg.ProgressPct,
		arg.CompletedCount,
	)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks
SET status = $3, updated_at = now()
WHERE id = $1 AND company_id = $2
`

type UpdateTaskStatusParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	Status    string    `json:"status"`
}

// Update a task's status.
func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.ID, arg.CompanyID, arg.Status)
	return err
}
