// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const assignNavigatorToTeam = `-- name: AssignNavigatorToTeam :exec
INSERT INTO team_assignments (super_navigator_id, navigator_id, company_id, assigned_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (super_navigator_id, navigator_id) DO NOTHING
`

type AssignNavigatorToTeamParams struct {
	SuperNavigatorID uuid.UUID `json:"super_navigator_id"`
	NavigatorID      uuid.UUID `json:"navigator_id"`
	CompanyID        uuid.UUID `json:"company_id"`
	AssignedBy       uuid.UUID `json:"assigned_by"`
}

func (q *Queries) AssignNavigatorToTeam(ctx context.Context, arg AssignNavigatorToTeamParams) error {
	_, err := q.db.Exec(ctx, assignNavigatorToTeam,
		arg.SuperNavigatorID,
		arg.NavigatorID,
		arg.CompanyID,
		arg.AssignedBy,
	)
	return err
}

const getTeamNavigators = `-- name: GetTeamNavigators :many
SELECT tea.navigator_id, u.email, u.display_name
FROM team_assignments tea
JOIN users u ON u.id = tea.navigator_id
WHERE tea.super_navigator_id = $1
`

type GetTeamNavigatorsRow struct {
	NavigatorID uuid.UUID `json:"navigator_id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) GetTeamNavigators(ctx context.Context, superNavigatorID uuid.UUID) ([]GetTeamNavigatorsRow, error) {
	rows, err := q.db.Query(ctx, getTeamNavigators, superNavigatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTeamNavigatorsRow{}
	for rows.Next() {
		var i GetTeamNavigatorsRow
		if err := rows.Scan(&i.NavigatorID, &i.Email, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamTurfIDs = `-- name: GetTeamTurfIDs :many
SELECT DISTINCT ta.turf_id
FROM team_assignments tea
JOIN turf_assignments ta ON ta.user_id = tea.navigator_id
WHERE tea.super_navigator_id = $1
`

// Returns all turf IDs for all navigators assigned to a super navigator.
func (q *Queries) GetTeamTurfIDs(ctx context.Context, superNavigatorID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getTeamTurfIDs, superNavigatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var turf_id uuid.UUID
		if err := rows.Scan(&turf_id); err != nil {
			return nil, err
		}
		items = append(items, turf_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeNavigatorFromTeam = `-- name: RemoveNavigatorFromTeam :exec
DELETE FROM team_assignments WHERE super_navigator_id = $1 AND navigator_id = $2
`

type RemoveNavigatorFromTeamParams struct {
	SuperNavigatorID uuid.UUID `json:"super_navigator_id"`
	NavigatorID      uuid.UUID `json:"navigator_id"`
}

func (q *Queries) RemoveNavigatorFromTeam(ctx context.Context, arg RemoveNavigatorFromTeamParams) error {
	_, err := q.db.Exec(ctx, removeNavigatorFromTeam, arg.SuperNavigatorID, arg.NavigatorID)
	return err
}
