// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: turfs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignUserToTurf = `-- name: AssignUserToTurf :exec
INSERT INTO turf_assignments (turf_id, user_id, assigned_by)
VALUES ($1, $2, $3)
ON CONFLICT (turf_id, user_id) DO NOTHING
`

type AssignUserToTurfParams struct {
	TurfID     uuid.UUID `json:"turf_id"`
	UserID     uuid.UUID `json:"user_id"`
	AssignedBy uuid.UUID `json:"assigned_by"`
}

func (q *Queries) AssignUserToTurf(ctx context.Context, arg AssignUserToTurfParams) error {
	_, err := q.db.Exec(ctx, assignUserToTurf, arg.TurfID, arg.UserID, arg.AssignedBy)
	return err
}

const createTurf = `-- name: CreateTurf :one
INSERT INTO turfs (company_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, company_id, name, description, is_active, created_at, updated_at
`

type CreateTurfParams struct {
	CompanyID   uuid.UUID `json:"company_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

type CreateTurfRow struct {
	ID          uuid.UUID `json:"id"`
	CompanyID   uuid.UUID `json:"company_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateTurf(ctx context.Context, arg CreateTurfParams) (CreateTurfRow, error) {
	row := q.db.QueryRow(ctx, createTurf, arg.CompanyID, arg.Name, arg.Description)
	var i CreateTurfRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTurfAssignmentsForUser = `-- name: GetTurfAssignmentsForUser :many
SELECT ta.turf_id, t.name as turf_name
FROM turf_assignments ta
JOIN turfs t ON t.id = ta.turf_id
WHERE ta.user_id = $1
`

type GetTurfAssignmentsForUserRow struct {
	TurfID   uuid.UUID `json:"turf_id"`
	TurfName string    `json:"turf_name"`
}

func (q *Queries) GetTurfAssignmentsForUser(ctx context.Context, userID uuid.UUID) ([]GetTurfAssignmentsForUserRow, error) {
	rows, err := q.db.Query(ctx, getTurfAssignmentsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTurfAssignmentsForUserRow{}
	for rows.Next() {
		var i GetTurfAssignmentsForUserRow
		if err := rows.Scan(&i.TurfID, &i.TurfName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTurfsByCompany = `-- name: GetTurfsByCompany :many
SELECT id, company_id, name, description, is_active, created_at, updated_at
FROM turfs WHERE company_id = $1 AND is_active = true
`

type GetTurfsByCompanyRow struct {
	ID          uuid.UUID `json:"id"`
	CompanyID   uuid.UUID `json:"company_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) GetTurfsByCompany(ctx context.Context, companyID uuid.UUID) ([]GetTurfsByCompanyRow, error) {
	rows, err := q.db.Query(ctx, getTurfsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTurfsByCompanyRow{}
	for rows.Next() {
		var i GetTurfsByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTurfIDs = `-- name: GetUserTurfIDs :many
SELECT turf_id FROM turf_assignments WHERE user_id = $1
`

func (q *Queries) GetUserTurfIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getUserTurfIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var turf_id uuid.UUID
		if err := rows.Scan(&turf_id); err != nil {
			return nil, err
		}
		items = append(items, turf_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromTurf = `-- name: RemoveUserFromTurf :exec
DELETE FROM turf_assignments WHERE turf_id = $1 AND user_id = $2
`

type RemoveUserFromTurfParams struct {
	TurfID uuid.UUID `json:"turf_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveUserFromTurf(ctx context.Context, arg RemoveUserFromTurfParams) error {
	_, err := q.db.Exec(ctx, removeUserFromTurf, arg.TurfID, arg.UserID)
	return err
}
