// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: turfs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignUserToTurf = `-- name: AssignUserToTurf :exec
INSERT INTO turf_assignments (turf_id, user_id, assigned_by)
VALUES ($1, $2, $3)
ON CONFLICT (turf_id, user_id) DO NOTHING
`

type AssignUserToTurfParams struct {
	TurfID     uuid.UUID `json:"turf_id"`
	UserID     uuid.UUID `json:"user_id"`
	AssignedBy uuid.UUID `json:"assigned_by"`
}

func (q *Queries) AssignUserToTurf(ctx context.Context, arg AssignUserToTurfParams) error {
	_, err := q.db.Exec(ctx, assignUserToTurf, arg.TurfID, arg.UserID, arg.AssignedBy)
	return err
}

const countVotersInTurf = `-- name: CountVotersInTurf :one
SELECT COUNT(*) FROM voters v
JOIN turfs t ON t.id = $1
WHERE v.company_id = $2
  AND v.location IS NOT NULL
  AND v.geocode_status = 'success'
  AND ST_Contains(t.boundary, v.location)
`

type CountVotersInTurfParams struct {
	TurfID    uuid.UUID `json:"turf_id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) CountVotersInTurf(ctx context.Context, arg CountVotersInTurfParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVotersInTurf, arg.TurfID, arg.CompanyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTurf = `-- name: CreateTurf :one
INSERT INTO turfs (company_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, company_id, name, description, is_active, created_at, updated_at
`

type CreateTurfParams struct {
	CompanyID   uuid.UUID `json:"company_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

type CreateTurfRow struct {
	ID          uuid.UUID `json:"id"`
	CompanyID   uuid.UUID `json:"company_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateTurf(ctx context.Context, arg CreateTurfParams) (CreateTurfRow, error) {
	row := q.db.QueryRow(ctx, createTurf, arg.CompanyID, arg.Name, arg.Description)
	var i CreateTurfRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTurfWithBoundary = `-- name: CreateTurfWithBoundary :one
INSERT INTO turfs (company_id, name, description, boundary)
VALUES ($1, $2, $3, ST_ForcePolygonCCW(ST_GeomFromGeoJSON($4)))
RETURNING id, company_id, name, description, is_active,
    ST_AsGeoJSON(boundary) as boundary_geojson,
    ST_Y(ST_Centroid(boundary)) as center_lat,
    ST_X(ST_Centroid(boundary)) as center_lng,
    ST_Area(boundary::geography) as area_sq_meters,
    created_at, updated_at
`

type CreateTurfWithBoundaryParams struct {
	CompanyID       uuid.UUID   `json:"company_id"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	BoundaryGeojson interface{} `json:"boundary_geojson"`
}

type CreateTurfWithBoundaryRow struct {
	ID              uuid.UUID   `json:"id"`
	CompanyID       uuid.UUID   `json:"company_id"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	IsActive        bool        `json:"is_active"`
	BoundaryGeojson interface{} `json:"boundary_geojson"`
	CenterLat       interface{} `json:"center_lat"`
	CenterLng       interface{} `json:"center_lng"`
	AreaSqMeters    interface{} `json:"area_sq_meters"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

func (q *Queries) CreateTurfWithBoundary(ctx context.Context, arg CreateTurfWithBoundaryParams) (CreateTurfWithBoundaryRow, error) {
	row := q.db.QueryRow(ctx, createTurfWithBoundary,
		arg.CompanyID,
		arg.Name,
		arg.Description,
		arg.BoundaryGeojson,
	)
	var i CreateTurfWithBoundaryRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.BoundaryGeojson,
		&i.CenterLat,
		&i.CenterLng,
		&i.AreaSqMeters,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTurfAssignmentsForUser = `-- name: GetTurfAssignmentsForUser :many
SELECT ta.turf_id, t.name as turf_name
FROM turf_assignments ta
JOIN turfs t ON t.id = ta.turf_id
WHERE ta.user_id = $1
`

type GetTurfAssignmentsForUserRow struct {
	TurfID   uuid.UUID `json:"turf_id"`
	TurfName string    `json:"turf_name"`
}

func (q *Queries) GetTurfAssignmentsForUser(ctx context.Context, userID uuid.UUID) ([]GetTurfAssignmentsForUserRow, error) {
	rows, err := q.db.Query(ctx, getTurfAssignmentsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTurfAssignmentsForUserRow{}
	for rows.Next() {
		var i GetTurfAssignmentsForUserRow
		if err := rows.Scan(&i.TurfID, &i.TurfName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTurfByID = `-- name: GetTurfByID :one
SELECT t.id, t.company_id, t.name, t.description, t.is_active,
    ST_AsGeoJSON(t.boundary) as boundary_geojson,
    ST_Y(ST_Centroid(t.boundary)) as center_lat,
    ST_X(ST_Centroid(t.boundary)) as center_lng,
    ST_Area(t.boundary::geography) as area_sq_meters,
    (SELECT COUNT(*) FROM voters v
     WHERE v.company_id = t.company_id
       AND v.location IS NOT NULL
       AND v.geocode_status = 'success'
       AND ST_Contains(t.boundary, v.location))::bigint as voter_count,
    t.created_at, t.updated_at
FROM turfs t
WHERE t.id = $1 AND t.company_id = $2
`

type GetTurfByIDParams struct {
	TurfID    uuid.UUID `json:"turf_id"`
	CompanyID uuid.UUID `json:"company_id"`
}

type GetTurfByIDRow struct {
	ID              uuid.UUID   `json:"id"`
	CompanyID       uuid.UUID   `json:"company_id"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	IsActive        bool        `json:"is_active"`
	BoundaryGeojson interface{} `json:"boundary_geojson"`
	CenterLat       interface{} `json:"center_lat"`
	CenterLng       interface{} `json:"center_lng"`
	AreaSqMeters    interface{} `json:"area_sq_meters"`
	VoterCount      int64       `json:"voter_count"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

func (q *Queries) GetTurfByID(ctx context.Context, arg GetTurfByIDParams) (GetTurfByIDRow, error) {
	row := q.db.QueryRow(ctx, getTurfByID, arg.TurfID, arg.CompanyID)
	var i GetTurfByIDRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.BoundaryGeojson,
		&i.CenterLat,
		&i.CenterLng,
		&i.AreaSqMeters,
		&i.VoterCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTurfCompletionStats = `-- name: GetTurfCompletionStats :one
SELECT
    COUNT(DISTINCT v.id)::bigint as total_voters,
    COUNT(DISTINCT cl.voter_id)::bigint as contacted_voters
FROM voters v
JOIN turfs t ON t.id = $1
LEFT JOIN contact_logs cl ON cl.voter_id = v.id AND cl.turf_id = $1
WHERE v.company_id = $2
  AND v.location IS NOT NULL
  AND v.geocode_status = 'success'
  AND ST_Contains(t.boundary, v.location)
`

type GetTurfCompletionStatsParams struct {
	TurfID    uuid.UUID `json:"turf_id"`
	CompanyID uuid.UUID `json:"company_id"`
}

type GetTurfCompletionStatsRow struct {
	TotalVoters     int64 `json:"total_voters"`
	ContactedVoters int64 `json:"contacted_voters"`
}

func (q *Queries) GetTurfCompletionStats(ctx context.Context, arg GetTurfCompletionStatsParams) (GetTurfCompletionStatsRow, error) {
	row := q.db.QueryRow(ctx, getTurfCompletionStats, arg.TurfID, arg.CompanyID)
	var i GetTurfCompletionStatsRow
	err := row.Scan(&i.TotalVoters, &i.ContactedVoters)
	return i, err
}

const getTurfsByCompany = `-- name: GetTurfsByCompany :many
SELECT id, company_id, name, description, is_active, created_at, updated_at
FROM turfs WHERE company_id = $1 AND is_active = true
`

type GetTurfsByCompanyRow struct {
	ID          uuid.UUID `json:"id"`
	CompanyID   uuid.UUID `json:"company_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) GetTurfsByCompany(ctx context.Context, companyID uuid.UUID) ([]GetTurfsByCompanyRow, error) {
	rows, err := q.db.Query(ctx, getTurfsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTurfsByCompanyRow{}
	for rows.Next() {
		var i GetTurfsByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTurfsByCompanyWithBoundary = `-- name: GetTurfsByCompanyWithBoundary :many
SELECT t.id, t.company_id, t.name, t.description, t.is_active,
    ST_AsGeoJSON(t.boundary) as boundary_geojson,
    ST_Y(ST_Centroid(t.boundary)) as center_lat,
    ST_X(ST_Centroid(t.boundary)) as center_lng,
    ST_Area(t.boundary::geography) as area_sq_meters,
    (SELECT COUNT(*) FROM voters v
     WHERE v.company_id = t.company_id
       AND v.location IS NOT NULL
       AND v.geocode_status = 'success'
       AND ST_Contains(t.boundary, v.location))::bigint as voter_count,
    t.created_at, t.updated_at
FROM turfs t
WHERE t.company_id = $1 AND t.is_active = true
`

type GetTurfsByCompanyWithBoundaryRow struct {
	ID              uuid.UUID   `json:"id"`
	CompanyID       uuid.UUID   `json:"company_id"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	IsActive        bool        `json:"is_active"`
	BoundaryGeojson interface{} `json:"boundary_geojson"`
	CenterLat       interface{} `json:"center_lat"`
	CenterLng       interface{} `json:"center_lng"`
	AreaSqMeters    interface{} `json:"area_sq_meters"`
	VoterCount      int64       `json:"voter_count"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

func (q *Queries) GetTurfsByCompanyWithBoundary(ctx context.Context, companyID uuid.UUID) ([]GetTurfsByCompanyWithBoundaryRow, error) {
	rows, err := q.db.Query(ctx, getTurfsByCompanyWithBoundary, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTurfsByCompanyWithBoundaryRow{}
	for rows.Next() {
		var i GetTurfsByCompanyWithBoundaryRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.BoundaryGeojson,
			&i.CenterLat,
			&i.CenterLng,
			&i.AreaSqMeters,
			&i.VoterCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTurfIDs = `-- name: GetUserTurfIDs :many
SELECT turf_id FROM turf_assignments WHERE user_id = $1
`

func (q *Queries) GetUserTurfIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getUserTurfIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var turf_id uuid.UUID
		if err := rows.Scan(&turf_id); err != nil {
			return nil, err
		}
		items = append(items, turf_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromTurf = `-- name: RemoveUserFromTurf :exec
DELETE FROM turf_assignments WHERE turf_id = $1 AND user_id = $2
`

type RemoveUserFromTurfParams struct {
	TurfID uuid.UUID `json:"turf_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveUserFromTurf(ctx context.Context, arg RemoveUserFromTurfParams) error {
	_, err := q.db.Exec(ctx, removeUserFromTurf, arg.TurfID, arg.UserID)
	return err
}

const updateTurfBoundary = `-- name: UpdateTurfBoundary :one
UPDATE turfs
SET boundary = ST_ForcePolygonCCW(ST_GeomFromGeoJSON($1)),
    updated_at = now()
WHERE id = $2 AND company_id = $3
RETURNING id, company_id, name, description, is_active,
    ST_AsGeoJSON(boundary) as boundary_geojson,
    ST_Y(ST_Centroid(boundary)) as center_lat,
    ST_X(ST_Centroid(boundary)) as center_lng,
    ST_Area(boundary::geography) as area_sq_meters,
    created_at, updated_at
`

type UpdateTurfBoundaryParams struct {
	BoundaryGeojson interface{} `json:"boundary_geojson"`
	TurfID          uuid.UUID   `json:"turf_id"`
	CompanyID       uuid.UUID   `json:"company_id"`
}

type UpdateTurfBoundaryRow struct {
	ID              uuid.UUID   `json:"id"`
	CompanyID       uuid.UUID   `json:"company_id"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	IsActive        bool        `json:"is_active"`
	BoundaryGeojson interface{} `json:"boundary_geojson"`
	CenterLat       interface{} `json:"center_lat"`
	CenterLng       interface{} `json:"center_lng"`
	AreaSqMeters    interface{} `json:"area_sq_meters"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateTurfBoundary(ctx context.Context, arg UpdateTurfBoundaryParams) (UpdateTurfBoundaryRow, error) {
	row := q.db.QueryRow(ctx, updateTurfBoundary, arg.BoundaryGeojson, arg.TurfID, arg.CompanyID)
	var i UpdateTurfBoundaryRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.BoundaryGeojson,
		&i.CenterLat,
		&i.CenterLng,
		&i.AreaSqMeters,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
