// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: volunteers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const completeOnboarding = `-- name: CompleteOnboarding :one
UPDATE navigator_profiles
SET onboarding_completed_at = now(),
    updated_at = now()
WHERE user_id = $1
RETURNING user_id, company_id, onboarding_completed_at, legal_acknowledgment_at, legal_acknowledgment_version, leaderboard_opt_in, created_at, updated_at
`

// Mark onboarding as complete, gating app access.
func (q *Queries) CompleteOnboarding(ctx context.Context, userID uuid.UUID) (NavigatorProfile, error) {
	row := q.db.QueryRow(ctx, completeOnboarding, userID)
	var i NavigatorProfile
	err := row.Scan(
		&i.UserID,
		&i.CompanyID,
		&i.OnboardingCompletedAt,
		&i.LegalAcknowledgmentAt,
		&i.LegalAcknowledgmentVersion,
		&i.LeaderboardOptIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrainingMaterial = `-- name: CreateTrainingMaterial :one
INSERT INTO training_materials (company_id, title, description, content_url, sort_order, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, title, description, content_url, sort_order, is_published, created_by, created_at, updated_at
`

type CreateTrainingMaterialParams struct {
	CompanyID   uuid.UUID `json:"company_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	ContentUrl  string    `json:"content_url"`
	SortOrder   int32     `json:"sort_order"`
	CreatedBy   uuid.UUID `json:"created_by"`
}

// Create a new training material entry.
func (q *Queries) CreateTrainingMaterial(ctx context.Context, arg CreateTrainingMaterialParams) (TrainingMaterial, error) {
	row := q.db.QueryRow(ctx, createTrainingMaterial,
		arg.CompanyID,
		arg.Title,
		arg.Description,
		arg.ContentUrl,
		arg.SortOrder,
		arg.CreatedBy,
	)
	var i TrainingMaterial
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.ContentUrl,
		&i.SortOrder,
		&i.IsPublished,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT
    np.user_id,
    u.display_name,
    COALESCE(SUM(CASE WHEN cl.contact_type = 'door_knock' THEN 1 ELSE 0 END), 0)::int AS doors_knocked,
    COALESCE(SUM(CASE WHEN cl.contact_type = 'text' THEN 1 ELSE 0 END), 0)::int AS texts_sent,
    COALESCE(SUM(CASE WHEN cl.contact_type = 'phone' THEN 1 ELSE 0 END), 0)::int AS calls_made,
    COALESCE(COUNT(cl.id), 0)::int AS total_actions,
    COALESCE((SELECT COUNT(*) FROM event_checkins ec
              JOIN events e ON e.id = ec.event_id
              WHERE ec.user_id = np.user_id
                AND e.company_id = $1
                AND ec.checked_in_at >= $2), 0)::int AS events_attended
FROM navigator_profiles np
JOIN users u ON u.id = np.user_id
LEFT JOIN contact_logs cl ON cl.user_id = np.user_id
    AND cl.company_id = $1
    AND cl.created_at >= $2
WHERE np.company_id = $1
  AND np.leaderboard_opt_in = true
GROUP BY np.user_id, u.display_name
ORDER BY total_actions DESC
`

type GetLeaderboardParams struct {
	CompanyID   uuid.UUID `json:"company_id"`
	CheckedInAt time.Time `json:"checked_in_at"`
}

type GetLeaderboardRow struct {
	UserID         uuid.UUID `json:"user_id"`
	DisplayName    string    `json:"display_name"`
	DoorsKnocked   int32     `json:"doors_knocked"`
	TextsSent      int32     `json:"texts_sent"`
	CallsMade      int32     `json:"calls_made"`
	TotalActions   int32     `json:"total_actions"`
	EventsAttended int32     `json:"events_attended"`
}

// Aggregated leaderboard query for opted-in navigators within a company and time window.
func (q *Queries) GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]GetLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboard, arg.CompanyID, arg.CheckedInAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeaderboardRow{}
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.DoorsKnocked,
			&i.TextsSent,
			&i.CallsMade,
			&i.TotalActions,
			&i.EventsAttended,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNavigatorProfile = `-- name: GetNavigatorProfile :one
SELECT user_id, company_id, onboarding_completed_at, legal_acknowledgment_at, legal_acknowledgment_version, leaderboard_opt_in, created_at, updated_at FROM navigator_profiles
WHERE user_id = $1 AND company_id = $2
`

type GetNavigatorProfileParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CompanyID uuid.UUID `json:"company_id"`
}

// Get a navigator profile by user_id and company_id.
func (q *Queries) GetNavigatorProfile(ctx context.Context, arg GetNavigatorProfileParams) (NavigatorProfile, error) {
	row := q.db.QueryRow(ctx, getNavigatorProfile, arg.UserID, arg.CompanyID)
	var i NavigatorProfile
	err := row.Scan(
		&i.UserID,
		&i.CompanyID,
		&i.OnboardingCompletedAt,
		&i.LegalAcknowledgmentAt,
		&i.LegalAcknowledgmentVersion,
		&i.LeaderboardOptIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrainingMaterial = `-- name: GetTrainingMaterial :one
SELECT id, company_id, title, description, content_url, sort_order, is_published, created_by, created_at, updated_at FROM training_materials
WHERE id = $1
`

// Get a training material by ID.
func (q *Queries) GetTrainingMaterial(ctx context.Context, id uuid.UUID) (TrainingMaterial, error) {
	row := q.db.QueryRow(ctx, getTrainingMaterial, id)
	var i TrainingMaterial
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.ContentUrl,
		&i.SortOrder,
		&i.IsPublished,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTrainingMaterials = `-- name: ListTrainingMaterials :many
SELECT id, company_id, title, description, content_url, sort_order, is_published, created_by, created_at, updated_at FROM training_materials
WHERE company_id = $1 AND is_published = true
ORDER BY sort_order
`

// List published training materials for a company, ordered by sort_order.
func (q *Queries) ListTrainingMaterials(ctx context.Context, companyID uuid.UUID) ([]TrainingMaterial, error) {
	rows, err := q.db.Query(ctx, listTrainingMaterials, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainingMaterial{}
	for rows.Next() {
		var i TrainingMaterial
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.ContentUrl,
			&i.SortOrder,
			&i.IsPublished,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLeaderboardOptIn = `-- name: UpdateLeaderboardOptIn :exec
UPDATE navigator_profiles
SET leaderboard_opt_in = $2,
    updated_at = now()
WHERE user_id = $1
`

type UpdateLeaderboardOptInParams struct {
	UserID           uuid.UUID `json:"user_id"`
	LeaderboardOptIn bool      `json:"leaderboard_opt_in"`
}

// Toggle leaderboard participation.
func (q *Queries) UpdateLeaderboardOptIn(ctx context.Context, arg UpdateLeaderboardOptInParams) error {
	_, err := q.db.Exec(ctx, updateLeaderboardOptIn, arg.UserID, arg.LeaderboardOptIn)
	return err
}

const updateLegalAcknowledgment = `-- name: UpdateLegalAcknowledgment :exec
UPDATE navigator_profiles
SET legal_acknowledgment_at = now(),
    legal_acknowledgment_version = $2,
    updated_at = now()
WHERE user_id = $1
`

type UpdateLegalAcknowledgmentParams struct {
	UserID                     uuid.UUID `json:"user_id"`
	LegalAcknowledgmentVersion *string   `json:"legal_acknowledgment_version"`
}

// Record a legal acknowledgment with version string for audit.
func (q *Queries) UpdateLegalAcknowledgment(ctx context.Context, arg UpdateLegalAcknowledgmentParams) error {
	_, err := q.db.Exec(ctx, updateLegalAcknowledgment, arg.UserID, arg.LegalAcknowledgmentVersion)
	return err
}

const upsertNavigatorProfile = `-- name: UpsertNavigatorProfile :one
INSERT INTO navigator_profiles (user_id, company_id)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET updated_at = now()
RETURNING user_id, company_id, onboarding_completed_at, legal_acknowledgment_at, legal_acknowledgment_version, leaderboard_opt_in, created_at, updated_at
`

type UpsertNavigatorProfileParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CompanyID uuid.UUID `json:"company_id"`
}

// Create or update a navigator profile (initial profile creation).
func (q *Queries) UpsertNavigatorProfile(ctx context.Context, arg UpsertNavigatorProfileParams) (NavigatorProfile, error) {
	row := q.db.QueryRow(ctx, upsertNavigatorProfile, arg.UserID, arg.CompanyID)
	var i NavigatorProfile
	err := row.Scan(
		&i.UserID,
		&i.CompanyID,
		&i.OnboardingCompletedAt,
		&i.LegalAcknowledgmentAt,
		&i.LegalAcknowledgmentVersion,
		&i.LeaderboardOptIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
