// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voters.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countVotersByCompany = `-- name: CountVotersByCompany :one
SELECT COUNT(*) FROM voters WHERE company_id = $1
`

func (q *Queries) CountVotersByCompany(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVotersByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getVoterByID = `-- name: GetVoterByID :one
SELECT id, company_id, first_name, middle_name, last_name, suffix, year_of_birth, res_street_address, res_street_number, res_street_name, res_unit, res_city, res_state, res_zip, mail_street_address, mail_city, mail_state, mail_zip, party, status, registration_date, county, municipality, ward, precinct, congressional_district, state_senate_district, state_house_district, location, geocode_status, geocode_source, source_voter_id, source, dedup_key, voting_history, phone, email, search_text, created_at, updated_at FROM voters WHERE id = $1
`

func (q *Queries) GetVoterByID(ctx context.Context, id uuid.UUID) (Voter, error) {
	row := q.db.QueryRow(ctx, getVoterByID, id)
	var i Voter
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Suffix,
		&i.YearOfBirth,
		&i.ResStreetAddress,
		&i.ResStreetNumber,
		&i.ResStreetName,
		&i.ResUnit,
		&i.ResCity,
		&i.ResState,
		&i.ResZip,
		&i.MailStreetAddress,
		&i.MailCity,
		&i.MailState,
		&i.MailZip,
		&i.Party,
		&i.Status,
		&i.RegistrationDate,
		&i.County,
		&i.Municipality,
		&i.Ward,
		&i.Precinct,
		&i.CongressionalDistrict,
		&i.StateSenateDistrict,
		&i.StateHouseDistrict,
		&i.Location,
		&i.GeocodeStatus,
		&i.GeocodeSource,
		&i.SourceVoterID,
		&i.Source,
		&i.DedupKey,
		&i.VotingHistory,
		&i.Phone,
		&i.Email,
		&i.SearchText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoterBySourceID = `-- name: GetVoterBySourceID :one
SELECT id, company_id, first_name, middle_name, last_name, suffix, year_of_birth, res_street_address, res_street_number, res_street_name, res_unit, res_city, res_state, res_zip, mail_street_address, mail_city, mail_state, mail_zip, party, status, registration_date, county, municipality, ward, precinct, congressional_district, state_senate_district, state_house_district, location, geocode_status, geocode_source, source_voter_id, source, dedup_key, voting_history, phone, email, search_text, created_at, updated_at FROM voters WHERE company_id = $1 AND source_voter_id = $2
`

type GetVoterBySourceIDParams struct {
	CompanyID     uuid.UUID `json:"company_id"`
	SourceVoterID string    `json:"source_voter_id"`
}

func (q *Queries) GetVoterBySourceID(ctx context.Context, arg GetVoterBySourceIDParams) (Voter, error) {
	row := q.db.QueryRow(ctx, getVoterBySourceID, arg.CompanyID, arg.SourceVoterID)
	var i Voter
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Suffix,
		&i.YearOfBirth,
		&i.ResStreetAddress,
		&i.ResStreetNumber,
		&i.ResStreetName,
		&i.ResUnit,
		&i.ResCity,
		&i.ResState,
		&i.ResZip,
		&i.MailStreetAddress,
		&i.MailCity,
		&i.MailState,
		&i.MailZip,
		&i.Party,
		&i.Status,
		&i.RegistrationDate,
		&i.County,
		&i.Municipality,
		&i.Ward,
		&i.Precinct,
		&i.CongressionalDistrict,
		&i.StateSenateDistrict,
		&i.StateHouseDistrict,
		&i.Location,
		&i.GeocodeStatus,
		&i.GeocodeSource,
		&i.SourceVoterID,
		&i.Source,
		&i.DedupKey,
		&i.VotingHistory,
		&i.Phone,
		&i.Email,
		&i.SearchText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVoter = `-- name: InsertVoter :exec
INSERT INTO voters (
    company_id, first_name, middle_name, last_name, suffix, year_of_birth,
    res_street_address, res_street_number, res_street_name, res_unit,
    res_city, res_state, res_zip,
    mail_street_address, mail_city, mail_state, mail_zip,
    party, status, registration_date,
    county, municipality, ward, precinct,
    congressional_district, state_senate_district, state_house_district,
    source_voter_id, source, dedup_key, voting_history,
    phone, email
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16, $17,
    $18, $19, $20,
    $21, $22, $23, $24,
    $25, $26, $27,
    $28, $29, $30, $31,
    $32, $33
) ON CONFLICT (company_id, dedup_key) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    middle_name = EXCLUDED.middle_name,
    suffix = EXCLUDED.suffix,
    res_street_address = EXCLUDED.res_street_address,
    res_unit = EXCLUDED.res_unit,
    res_city = EXCLUDED.res_city,
    res_state = EXCLUDED.res_state,
    res_zip = EXCLUDED.res_zip,
    mail_street_address = EXCLUDED.mail_street_address,
    mail_city = EXCLUDED.mail_city,
    mail_state = EXCLUDED.mail_state,
    mail_zip = EXCLUDED.mail_zip,
    party = EXCLUDED.party,
    status = EXCLUDED.status,
    registration_date = EXCLUDED.registration_date,
    county = EXCLUDED.county,
    municipality = EXCLUDED.municipality,
    ward = EXCLUDED.ward,
    precinct = EXCLUDED.precinct,
    congressional_district = EXCLUDED.congressional_district,
    state_senate_district = EXCLUDED.state_senate_district,
    state_house_district = EXCLUDED.state_house_district,
    source_voter_id = EXCLUDED.source_voter_id,
    source = EXCLUDED.source,
    voting_history = EXCLUDED.voting_history,
    phone = EXCLUDED.phone,
    email = EXCLUDED.email,
    updated_at = now()
`

type InsertVoterParams struct {
	CompanyID             uuid.UUID       `json:"company_id"`
	FirstName             string          `json:"first_name"`
	MiddleName            string          `json:"middle_name"`
	LastName              string          `json:"last_name"`
	Suffix                string          `json:"suffix"`
	YearOfBirth           *int32          `json:"year_of_birth"`
	ResStreetAddress      string          `json:"res_street_address"`
	ResStreetNumber       string          `json:"res_street_number"`
	ResStreetName         string          `json:"res_street_name"`
	ResUnit               string          `json:"res_unit"`
	ResCity               string          `json:"res_city"`
	ResState              string          `json:"res_state"`
	ResZip                string          `json:"res_zip"`
	MailStreetAddress     string          `json:"mail_street_address"`
	MailCity              string          `json:"mail_city"`
	MailState             string          `json:"mail_state"`
	MailZip               string          `json:"mail_zip"`
	Party                 string          `json:"party"`
	Status                string          `json:"status"`
	RegistrationDate      string          `json:"registration_date"`
	County                string          `json:"county"`
	Municipality          string          `json:"municipality"`
	Ward                  string          `json:"ward"`
	Precinct              string          `json:"precinct"`
	CongressionalDistrict string          `json:"congressional_district"`
	StateSenateDistrict   string          `json:"state_senate_district"`
	StateHouseDistrict    string          `json:"state_house_district"`
	SourceVoterID         string          `json:"source_voter_id"`
	Source                string          `json:"source"`
	DedupKey              string          `json:"dedup_key"`
	VotingHistory         json.RawMessage `json:"voting_history"`
	Phone                 string          `json:"phone"`
	Email                 string          `json:"email"`
}

func (q *Queries) InsertVoter(ctx context.Context, arg InsertVoterParams) error {
	_, err := q.db.Exec(ctx, insertVoter,
		arg.CompanyID,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.Suffix,
		arg.YearOfBirth,
		arg.ResStreetAddress,
		arg.ResStreetNumber,
		arg.ResStreetName,
		arg.ResUnit,
		arg.ResCity,
		arg.ResState,
		arg.ResZip,
		arg.MailStreetAddress,
		arg.MailCity,
		arg.MailState,
		arg.MailZip,
		arg.Party,
		arg.Status,
		arg.RegistrationDate,
		arg.County,
		arg.Municipality,
		arg.Ward,
		arg.Precinct,
		arg.CongressionalDistrict,
		arg.StateSenateDistrict,
		arg.StateHouseDistrict,
		arg.SourceVoterID,
		arg.Source,
		arg.DedupKey,
		arg.VotingHistory,
		arg.Phone,
		arg.Email,
	)
	return err
}
