// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voter_notes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getVoterNotesForVoterByRole = `-- name: GetVoterNotesForVoterByRole :many
SELECT id, company_id, voter_id, user_id, turf_id, content, visibility, created_at, updated_at FROM voter_notes
WHERE voter_id = $1 AND company_id = $2
  AND (
    -- Admin sees all
    $3 >= 80
    -- SuperNav sees org + team
    OR ($3 >= 60 AND visibility IN ('org', 'team'))
    -- Navigator sees org + own
    OR (visibility = 'org')
    OR (user_id = $4)
  )
ORDER BY created_at DESC
`

type GetVoterNotesForVoterByRoleParams struct {
	VoterID   uuid.UUID   `json:"voter_id"`
	CompanyID uuid.UUID   `json:"company_id"`
	Column3   interface{} `json:"column_3"`
	UserID    uuid.UUID   `json:"user_id"`
}

// Get voter notes for a voter, scoped by role level.
// $3 = role_level (int), $4 = requesting user_id
// Admin (>=80) sees all notes for the voter.
// SuperNav (>=60) sees 'org' + 'team' notes for the voter.
// Navigator (<60) sees 'org' notes + own notes.
func (q *Queries) GetVoterNotesForVoterByRole(ctx context.Context, arg GetVoterNotesForVoterByRoleParams) ([]VoterNote, error) {
	rows, err := q.db.Query(ctx, getVoterNotesForVoterByRole,
		arg.VoterID,
		arg.CompanyID,
		arg.Column3,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoterNote{}
	for rows.Next() {
		var i VoterNote
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.VoterID,
			&i.UserID,
			&i.TurfID,
			&i.Content,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVoterNoteFromSync = `-- name: UpsertVoterNoteFromSync :exec
INSERT INTO voter_notes (id, company_id, voter_id, user_id, turf_id, content, visibility, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO NOTHING
`

type UpsertVoterNoteFromSyncParams struct {
	ID         uuid.UUID   `json:"id"`
	CompanyID  uuid.UUID   `json:"company_id"`
	VoterID    uuid.UUID   `json:"voter_id"`
	UserID     uuid.UUID   `json:"user_id"`
	TurfID     pgtype.UUID `json:"turf_id"`
	Content    string      `json:"content"`
	Visibility string      `json:"visibility"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

// Insert a voter note from a client sync push. Append-only: skip if already exists.
func (q *Queries) UpsertVoterNoteFromSync(ctx context.Context, arg UpsertVoterNoteFromSyncParams) error {
	_, err := q.db.Exec(ctx, upsertVoterNoteFromSync,
		arg.ID,
		arg.CompanyID,
		arg.VoterID,
		arg.UserID,
		arg.TurfID,
		arg.Content,
		arg.Visibility,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
